package pams.repo4odsbpbs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repo4odsbpbs.model.QdbgGjCustInfoAll;
import pams.repo4odsbpbs.model.QdbgGjCustInfoAllExample;

@Component
public interface QdbgGjCustInfoAllMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    int countByExample(QdbgGjCustInfoAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    int deleteByExample(QdbgGjCustInfoAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    int deleteByPrimaryKey(String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    int insert(QdbgGjCustInfoAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    int insertSelective(QdbgGjCustInfoAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    List<QdbgGjCustInfoAll> selectByExample(QdbgGjCustInfoAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    QdbgGjCustInfoAll selectByPrimaryKey(String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") QdbgGjCustInfoAll record, @Param("example") QdbgGjCustInfoAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    int updateByExample(@Param("record") QdbgGjCustInfoAll record, @Param("example") QdbgGjCustInfoAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    int updateByPrimaryKeySelective(QdbgGjCustInfoAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QDBG_GJ_CUST_INFO_ALL
     *
     * @mbggenerated Fri May 22 20:58:58 CST 2015
     */
    int updateByPrimaryKey(QdbgGjCustInfoAll record);
}