package pams.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.ClsUdTblinfo;
import pams.repository.model.ClsUdTblinfoExample;
import pams.repository.model.ClsUdTblinfoKey;
@Component
public interface ClsUdTblinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int countByExample(ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int deleteByExample(ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int deleteByPrimaryKey(ClsUdTblinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int insert(ClsUdTblinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int insertSelective(ClsUdTblinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    List<ClsUdTblinfo> selectByExample(ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    ClsUdTblinfo selectByPrimaryKey(ClsUdTblinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") ClsUdTblinfo record, @Param("example") ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int updateByExample(@Param("record") ClsUdTblinfo record, @Param("example") ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int updateByPrimaryKeySelective(ClsUdTblinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int updateByPrimaryKey(ClsUdTblinfo record);
}