package pams.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.ClsUdFeedback;
import pams.repository.model.ClsUdFeedbackExample;

@Component
public interface ClsUdFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    int countByExample(ClsUdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    int deleteByExample(ClsUdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    int insert(ClsUdFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    int insertSelective(ClsUdFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    List<ClsUdFeedback> selectByExample(ClsUdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    ClsUdFeedback selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    int updateByExampleSelective(@Param("record") ClsUdFeedback record, @Param("example") ClsUdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    int updateByExample(@Param("record") ClsUdFeedback record, @Param("example") ClsUdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    int updateByPrimaryKeySelective(ClsUdFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FEEDBACK
     *
     * @mbggenerated Sun May 24 14:04:37 CST 2015
     */
    int updateByPrimaryKey(ClsUdFeedback record);
}