package pams.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.ClsUdFldinfo;
import pams.repository.model.ClsUdFldinfoExample;
import pams.repository.model.ClsUdFldinfoKey;

@Component
public interface ClsUdFldinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int countByExample(ClsUdFldinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int deleteByExample(ClsUdFldinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int deleteByPrimaryKey(ClsUdFldinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int insert(ClsUdFldinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int insertSelective(ClsUdFldinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    List<ClsUdFldinfo> selectByExample(ClsUdFldinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    ClsUdFldinfo selectByPrimaryKey(ClsUdFldinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") ClsUdFldinfo record, @Param("example") ClsUdFldinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int updateByExample(@Param("record") ClsUdFldinfo record, @Param("example") ClsUdFldinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int updateByPrimaryKeySelective(ClsUdFldinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    int updateByPrimaryKey(ClsUdFldinfo record);
}