package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.ClsUdTblinfo;
import pams.repository.model.ClsUdTblinfoExample;

import java.util.List;

@Component
public interface ClsUdTblinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    int countByExample(ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    int deleteByExample(ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    int deleteByPrimaryKey(String rptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    int insert(ClsUdTblinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    int insertSelective(ClsUdTblinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    List<ClsUdTblinfo> selectByExample(ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    ClsUdTblinfo selectByPrimaryKey(String rptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    int updateByExampleSelective(@Param("record") ClsUdTblinfo record, @Param("example") ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    int updateByExample(@Param("record") ClsUdTblinfo record, @Param("example") ClsUdTblinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    int updateByPrimaryKeySelective(ClsUdTblinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    int updateByPrimaryKey(ClsUdTblinfo record);
}