package pams.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.ClsUdRptdata;
import pams.repository.model.ClsUdRptdataExample;

@Component
public interface ClsUdRptdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    int countByExample(ClsUdRptdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    int deleteByExample(ClsUdRptdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    int insert(ClsUdRptdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    int insertSelective(ClsUdRptdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    List<ClsUdRptdata> selectByExample(ClsUdRptdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    ClsUdRptdata selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") ClsUdRptdata record, @Param("example") ClsUdRptdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    int updateByExample(@Param("record") ClsUdRptdata record, @Param("example") ClsUdRptdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    int updateByPrimaryKeySelective(ClsUdRptdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_RPTDATA
     *
     * @mbggenerated Sun May 24 17:10:34 CST 2015
     */
    int updateByPrimaryKey(ClsUdRptdata record);
}