package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.OdsbChnTrad;
import pams.repository.model.OdsbChnTradExample;

import java.util.List;

@Component
public interface OdsbChnTradMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    int countByExample(OdsbChnTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    int deleteByExample(OdsbChnTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    int insert(OdsbChnTrad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    int insertSelective(OdsbChnTrad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    List<OdsbChnTrad> selectByExample(OdsbChnTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    OdsbChnTrad selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    int updateByExampleSelective(@Param("record") OdsbChnTrad record, @Param("example") OdsbChnTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    int updateByExample(@Param("record") OdsbChnTrad record, @Param("example") OdsbChnTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    int updateByPrimaryKeySelective(OdsbChnTrad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CHN_TRAD
     *
     * @mbggenerated Fri Feb 22 18:01:26 CST 2013
     */
    int updateByPrimaryKey(OdsbChnTrad record);
}