package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.OdsbPayagentTxn;
import pams.repository.model.OdsbPayagentTxnExample;

import java.util.List;

@Component
public interface OdsbPayagentTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    int countByExample(OdsbPayagentTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    int deleteByExample(OdsbPayagentTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    int insert(OdsbPayagentTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    int insertSelective(OdsbPayagentTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    List<OdsbPayagentTxn> selectByExample(OdsbPayagentTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    OdsbPayagentTxn selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    int updateByExampleSelective(@Param("record") OdsbPayagentTxn record, @Param("example") OdsbPayagentTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    int updateByExample(@Param("record") OdsbPayagentTxn record, @Param("example") OdsbPayagentTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    int updateByPrimaryKeySelective(OdsbPayagentTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    int updateByPrimaryKey(OdsbPayagentTxn record);
}