package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.OdsbStTconfirmTrad;
import pams.repository.model.OdsbStTconfirmTradExample;

import java.util.List;

@Component
public interface OdsbStTconfirmTradMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    int countByExample(OdsbStTconfirmTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    int deleteByExample(OdsbStTconfirmTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    int insert(OdsbStTconfirmTrad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    int insertSelective(OdsbStTconfirmTrad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    List<OdsbStTconfirmTrad> selectByExample(OdsbStTconfirmTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    int updateByExampleSelective(@Param("record") OdsbStTconfirmTrad record, @Param("example") OdsbStTconfirmTradExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    int updateByExample(@Param("record") OdsbStTconfirmTrad record, @Param("example") OdsbStTconfirmTradExample example);
}