package pams.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pams.repository.model.OdsbPldfDtl;
import pams.repository.model.OdsbPldfDtlExample;
import pams.repository.model.OdsbPldfDtlKey;

public interface OdsbPldfDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    int countByExample(OdsbPldfDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    int deleteByExample(OdsbPldfDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    int deleteByPrimaryKey(OdsbPldfDtlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    int insert(OdsbPldfDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    int insertSelective(OdsbPldfDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    List<OdsbPldfDtl> selectByExample(OdsbPldfDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    OdsbPldfDtl selectByPrimaryKey(OdsbPldfDtlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    int updateByExampleSelective(@Param("record") OdsbPldfDtl record, @Param("example") OdsbPldfDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    int updateByExample(@Param("record") OdsbPldfDtl record, @Param("example") OdsbPldfDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    int updateByPrimaryKeySelective(OdsbPldfDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PLDF_DTL
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    int updateByPrimaryKey(OdsbPldfDtl record);
}