package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.OdsbPayrollTxn;
import pams.repository.model.OdsbPayrollTxnExample;

import java.util.List;

@Component
public interface OdsbPayrollTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYROLL_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int countByExample(OdsbPayrollTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYROLL_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int deleteByExample(OdsbPayrollTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYROLL_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int insert(OdsbPayrollTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYROLL_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int insertSelective(OdsbPayrollTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYROLL_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    List<OdsbPayrollTxn> selectByExample(OdsbPayrollTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYROLL_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int updateByExampleSelective(@Param("record") OdsbPayrollTxn record, @Param("example") OdsbPayrollTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYROLL_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int updateByExample(@Param("record") OdsbPayrollTxn record, @Param("example") OdsbPayrollTxnExample example);
}