package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.OdsbHousingfundTxn;
import pams.repository.model.OdsbHousingfundTxnExample;

import java.util.List;

@Component
public interface OdsbHousingfundTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_HOUSINGFUND_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int countByExample(OdsbHousingfundTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_HOUSINGFUND_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int deleteByExample(OdsbHousingfundTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_HOUSINGFUND_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int insert(OdsbHousingfundTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_HOUSINGFUND_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int insertSelective(OdsbHousingfundTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_HOUSINGFUND_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    List<OdsbHousingfundTxn> selectByExample(OdsbHousingfundTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_HOUSINGFUND_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int updateByExampleSelective(@Param("record") OdsbHousingfundTxn record, @Param("example") OdsbHousingfundTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_HOUSINGFUND_TXN
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    int updateByExample(@Param("record") OdsbHousingfundTxn record, @Param("example") OdsbHousingfundTxnExample example);
}