package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Ptenumain;
import pams.repository.model.PtenumainExample;

import java.util.List;

@Component

public interface PtenumainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    int countByExample(PtenumainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    int deleteByExample(PtenumainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    int deleteByPrimaryKey(String enutype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    int insert(Ptenumain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    int insertSelective(Ptenumain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    List<Ptenumain> selectByExample(PtenumainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    Ptenumain selectByPrimaryKey(String enutype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    int updateByExampleSelective(@Param("record") Ptenumain record, @Param("example") PtenumainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    int updateByExample(@Param("record") Ptenumain record, @Param("example") PtenumainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    int updateByPrimaryKeySelective(Ptenumain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTENUMAIN
     *
     * @mbggenerated Sat Mar 19 22:33:44 CST 2011
     */
    int updateByPrimaryKey(Ptenumain record);
}