package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.SvEclCustinfo;
import pams.repository.model.SvEclCustinfoExample;

import java.util.List;

@Component
public interface SvEclCustinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    int countByExample(SvEclCustinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    int deleteByExample(SvEclCustinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    int insert(SvEclCustinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    int insertSelective(SvEclCustinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    List<SvEclCustinfo> selectByExample(SvEclCustinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    SvEclCustinfo selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    int updateByExampleSelective(@Param("record") SvEclCustinfo record, @Param("example") SvEclCustinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    int updateByExample(@Param("record") SvEclCustinfo record, @Param("example") SvEclCustinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    int updateByPrimaryKeySelective(SvEclCustinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_ECL_CUSTINFO
     *
     * @mbggenerated Tue Apr 23 16:21:41 CST 2013
     */
    int updateByPrimaryKey(SvEclCustinfo record);
}