package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svintvinf;
import pams.repository.model.SvintvinfExample;
import pams.repository.model.SvprdsalinfChd;

import java.util.List;

@Component
public interface SvintvinfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int countByExample(SvintvinfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int deleteByExample(SvintvinfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int insert(Svintvinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int insertSelective(Svintvinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    List<Svintvinf> selectByExample(SvintvinfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    Svintvinf selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svintvinf record, @Param("example") SvintvinfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int updateByExample(@Param("record") Svintvinf record, @Param("example") SvintvinfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int updateByPrimaryKeySelective(Svintvinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVINTVINF
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int updateByPrimaryKey(Svintvinf record);


}