package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svmeetinginf;
import pams.repository.model.SvmeetinginfExample;

import java.util.List;

@Component
public interface SvmeetinginfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    int countByExample(SvmeetinginfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    int deleteByExample(SvmeetinginfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    int insert(Svmeetinginf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    int insertSelective(Svmeetinginf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    List<Svmeetinginf> selectByExample(SvmeetinginfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    Svmeetinginf selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svmeetinginf record, @Param("example") SvmeetinginfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    int updateByExample(@Param("record") Svmeetinginf record, @Param("example") SvmeetinginfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    int updateByPrimaryKeySelective(Svmeetinginf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGINF
     *
     * @mbggenerated Fri Apr 01 14:56:53 CST 2011
     */
    int updateByPrimaryKey(Svmeetinginf record);

    /**
     * 自定义主键 zhanrui
     * @param record
     * @return
     */
    int insertByCustomKey(Svmeetinginf record);
    String selectKey();
}