package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svmeetingevent;
import pams.repository.model.SvmeetingeventExample;

import java.util.List;

@Component
public interface SvmeetingeventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    int countByExample(SvmeetingeventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    int deleteByExample(SvmeetingeventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    int insert(Svmeetingevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    int insertSelective(Svmeetingevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    List<Svmeetingevent> selectByExample(SvmeetingeventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    Svmeetingevent selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svmeetingevent record, @Param("example") SvmeetingeventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    int updateByExample(@Param("record") Svmeetingevent record, @Param("example") SvmeetingeventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    int updateByPrimaryKeySelective(Svmeetingevent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVMEETINGEVENT
     *
     * @mbggenerated Sat Apr 02 07:21:06 CST 2011
     */
    int updateByPrimaryKey(Svmeetingevent record);

    /**
     * zhanrui
     * @param branchid
     * @param startdate
     * @param enddate
     * @return
     */
    List<Svmeetingevent> selectSuccessEvents(@Param("branchid") String branchid,
                                             @Param("startdate") String startdate,
                                             @Param("enddate") String enddate);

    List<Svmeetingevent> selectRefuseEvents1(@Param("branchid") String branchid,
                                             @Param("startdate") String startdate,
                                             @Param("enddate") String enddate);

    List<Svmeetingevent> selectRefuseEvents2(@Param("branchid") String branchid,
                                             @Param("startdate") String startdate,
                                             @Param("enddate") String enddate);

    List<Svmeetingevent> selectRefuseEvents3(@Param("branchid") String branchid,
                                             @Param("startdate") String startdate,
                                             @Param("enddate") String enddate);

    int countSuccessEvents(@Param("branchid") String branchid,
                                             @Param("startdate") String startdate,
                                             @Param("enddate") String enddate);

}