package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.SvprdsalinfDel;
import pams.repository.model.SvprdsalinfDelExample;

import java.util.List;

@Component
public interface SvprdsalinfDelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int countByExample(SvprdsalinfDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int deleteByExample(SvprdsalinfDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int insert(SvprdsalinfDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int insertSelective(SvprdsalinfDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    List<SvprdsalinfDel> selectByExample(SvprdsalinfDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    SvprdsalinfDel selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int updateByExampleSelective(@Param("record") SvprdsalinfDel record, @Param("example") SvprdsalinfDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int updateByExample(@Param("record") SvprdsalinfDel record, @Param("example") SvprdsalinfDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int updateByPrimaryKeySelective(SvprdsalinfDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPRDSALINF_DEL
     *
     * @mbggenerated Fri Apr 29 10:31:02 CST 2011
     */
    int updateByPrimaryKey(SvprdsalinfDel record);
}