package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svpssaleprdinfo;
import pams.repository.model.SvpssaleprdinfoExample;

import java.util.List;

@Component
public interface SvpssaleprdinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    int countByExample(SvpssaleprdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    int deleteByExample(SvpssaleprdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    int insert(Svpssaleprdinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    int insertSelective(Svpssaleprdinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    List<Svpssaleprdinfo> selectByExample(SvpssaleprdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    Svpssaleprdinfo selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svpssaleprdinfo record, @Param("example") SvpssaleprdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    int updateByExample(@Param("record") Svpssaleprdinfo record, @Param("example") SvpssaleprdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    int updateByPrimaryKeySelective(Svpssaleprdinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDINFO
     *
     * @mbggenerated Sat May 21 20:03:12 CST 2011
     */
    int updateByPrimaryKey(Svpssaleprdinfo record);
}