package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svpsprdsetdetail;
import pams.repository.model.SvpsprdsetdetailExample;
import pams.repository.model.SvpsprdsetdetailKey;

import java.util.List;
@Component

public interface SvpsprdsetdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int countByExample(SvpsprdsetdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int deleteByExample(SvpsprdsetdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int deleteByPrimaryKey(SvpsprdsetdetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int insert(Svpsprdsetdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int insertSelective(Svpsprdsetdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    List<Svpsprdsetdetail> selectByExample(SvpsprdsetdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    Svpsprdsetdetail selectByPrimaryKey(SvpsprdsetdetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svpsprdsetdetail record, @Param("example") SvpsprdsetdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int updateByExample(@Param("record") Svpsprdsetdetail record, @Param("example") SvpsprdsetdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int updateByPrimaryKeySelective(Svpsprdsetdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETDETAIL
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int updateByPrimaryKey(Svpsprdsetdetail record);
}