package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svpssaleprdckpt;
import pams.repository.model.SvpssaleprdckptExample;

import java.util.List;

@Component
public interface SvpssaleprdckptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    int countByExample(SvpssaleprdckptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    int deleteByExample(SvpssaleprdckptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    int insert(Svpssaleprdckpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    int insertSelective(Svpssaleprdckpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    List<Svpssaleprdckpt> selectByExample(SvpssaleprdckptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    Svpssaleprdckpt selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svpssaleprdckpt record, @Param("example") SvpssaleprdckptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    int updateByExample(@Param("record") Svpssaleprdckpt record, @Param("example") SvpssaleprdckptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    int updateByPrimaryKeySelective(Svpssaleprdckpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEPRDCKPT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    int updateByPrimaryKey(Svpssaleprdckpt record);
}