package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svpssaleinfo;
import pams.repository.model.SvpssaleinfoExample;

import java.util.List;
@Component
public interface SvpssaleinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    int countByExample(SvpssaleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    int deleteByExample(SvpssaleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    int insert(Svpssaleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    int insertSelective(Svpssaleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    List<Svpssaleinfo> selectByExample(SvpssaleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    Svpssaleinfo selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svpssaleinfo record, @Param("example") SvpssaleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    int updateByExample(@Param("record") Svpssaleinfo record, @Param("example") SvpssaleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    int updateByPrimaryKeySelective(Svpssaleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSSALEINFO
     *
     * @mbggenerated Tue Apr 26 09:49:49 CST 2011
     */
    int updateByPrimaryKey(Svpssaleinfo record);


    //zhanrui ×Ô¿ØÖÆGUID
    String selectGuid();
    int insertByGuid(Svpssaleinfo record);
}