package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svpsprdckptdef;
import pams.repository.model.SvpsprdckptdefExample;

import java.util.List;

@Component
public interface SvpsprdckptdefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    int countByExample(SvpsprdckptdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    int deleteByExample(SvpsprdckptdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    int insert(Svpsprdckptdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    int insertSelective(Svpsprdckptdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    List<Svpsprdckptdef> selectByExample(SvpsprdckptdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    Svpsprdckptdef selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svpsprdckptdef record, @Param("example") SvpsprdckptdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    int updateByExample(@Param("record") Svpsprdckptdef record, @Param("example") SvpsprdckptdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    int updateByPrimaryKeySelective(Svpsprdckptdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDCKPTDEF
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    int updateByPrimaryKey(Svpsprdckptdef record);
}