package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svpsprdsetprice;
import pams.repository.model.SvpsprdsetpriceExample;

import java.util.List;
@Component

public interface SvpsprdsetpriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int countByExample(SvpsprdsetpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int deleteByExample(SvpsprdsetpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int deleteByPrimaryKey(String prdsetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int insert(Svpsprdsetprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int insertSelective(Svpsprdsetprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    List<Svpsprdsetprice> selectByExample(SvpsprdsetpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    Svpsprdsetprice selectByPrimaryKey(String prdsetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svpsprdsetprice record, @Param("example") SvpsprdsetpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int updateByExample(@Param("record") Svpsprdsetprice record, @Param("example") SvpsprdsetpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int updateByPrimaryKeySelective(Svpsprdsetprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETPRICE
     *
     * @mbggenerated Mon Apr 18 17:36:25 CST 2011
     */
    int updateByPrimaryKey(Svpsprdsetprice record);
}