package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.Svpsprdsetmain;
import pams.repository.model.SvpsprdsetmainExample;

import java.util.List;
@Component

public interface SvpsprdsetmainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    int countByExample(SvpsprdsetmainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    int deleteByExample(SvpsprdsetmainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    int deleteByPrimaryKey(String prdsetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    int insert(Svpsprdsetmain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    int insertSelective(Svpsprdsetmain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    List<Svpsprdsetmain> selectByExample(SvpsprdsetmainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    Svpsprdsetmain selectByPrimaryKey(String prdsetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    int updateByExampleSelective(@Param("record") Svpsprdsetmain record, @Param("example") SvpsprdsetmainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    int updateByExample(@Param("record") Svpsprdsetmain record, @Param("example") SvpsprdsetmainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    int updateByPrimaryKeySelective(Svpsprdsetmain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    int updateByPrimaryKey(Svpsprdsetmain record);
}