package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.SvSaleDetailHis;
import pams.repository.model.SvSaleDetailHisExample;

import java.util.List;

@Component
public interface SvSaleDetailHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    int countByExample(SvSaleDetailHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    int deleteByExample(SvSaleDetailHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    int insert(SvSaleDetailHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    int insertSelective(SvSaleDetailHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    List<SvSaleDetailHis> selectByExample(SvSaleDetailHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    SvSaleDetailHis selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    int updateByExampleSelective(@Param("record") SvSaleDetailHis record, @Param("example") SvSaleDetailHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    int updateByExample(@Param("record") SvSaleDetailHis record, @Param("example") SvSaleDetailHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    int updateByPrimaryKeySelective(SvSaleDetailHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL_HIS
     *
     * @mbggenerated Sun Jul 28 22:36:26 CST 2013
     */
    int updateByPrimaryKey(SvSaleDetailHis record);
}