package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.SvSaleDetail;
import pams.repository.model.SvSaleDetailExample;

import java.util.List;

@Component
public interface SvSaleDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    int countByExample(SvSaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    int deleteByExample(SvSaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    int insert(SvSaleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    int insertSelective(SvSaleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    List<SvSaleDetail> selectByExample(SvSaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    SvSaleDetail selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    int updateByExampleSelective(@Param("record") SvSaleDetail record, @Param("example") SvSaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    int updateByExample(@Param("record") SvSaleDetail record, @Param("example") SvSaleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    int updateByPrimaryKeySelective(SvSaleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_SALE_DETAIL
     *
     * @mbggenerated Wed Feb 06 17:09:02 CST 2013
     */
    int updateByPrimaryKey(SvSaleDetail record);
}