package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.SysBbs;
import pams.repository.model.SysBbsExample;

import java.util.List;

@Component
public interface SysBbsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    int countByExample(SysBbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    int deleteByExample(SysBbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    int insert(SysBbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    int insertSelective(SysBbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    List<SysBbs> selectByExample(SysBbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    SysBbs selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    int updateByExampleSelective(@Param("record") SysBbs record, @Param("example") SysBbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    int updateByExample(@Param("record") SysBbs record, @Param("example") SysBbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    int updateByPrimaryKeySelective(SysBbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BBS
     *
     * @mbggenerated Mon Jul 29 11:41:31 CST 2013
     */
    int updateByPrimaryKey(SysBbs record);
}