package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.SysLock;
import pams.repository.model.SysLockExample;

import java.util.List;

@Component

public interface SysLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int countByExample(SysLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int deleteByExample(SysLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int insert(SysLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int insertSelective(SysLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    List<SysLock> selectByExample(SysLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int updateByExampleSelective(@Param("record") SysLock record, @Param("example") SysLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int updateByExample(@Param("record") SysLock record, @Param("example") SysLockExample example);
}