package pams.repository.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import pams.repository.model.SysScheduler;
import pams.repository.model.SysSchedulerExample;

import java.util.List;

@Component

public interface SysSchedulerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int countByExample(SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int deleteByExample(SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int insert(SysScheduler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int insertSelective(SysScheduler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    List<SysScheduler> selectByExample(SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int updateByExampleSelective(@Param("record") SysScheduler record, @Param("example") SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SCHEDULER
     *
     * @mbggenerated Sat Mar 19 22:33:45 CST 2011
     */
    int updateByExample(@Param("record") SysScheduler record, @Param("example") SysSchedulerExample example);
}