package pams.repository.model;

import java.util.ArrayList;
import java.util.List;

public class ClsUdTblinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public ClsUdTblinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRptnoIsNull() {
            addCriterion("RPTNO is null");
            return (Criteria) this;
        }

        public Criteria andRptnoIsNotNull() {
            addCriterion("RPTNO is not null");
            return (Criteria) this;
        }

        public Criteria andRptnoEqualTo(String value) {
            addCriterion("RPTNO =", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotEqualTo(String value) {
            addCriterion("RPTNO <>", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoGreaterThan(String value) {
            addCriterion("RPTNO >", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoGreaterThanOrEqualTo(String value) {
            addCriterion("RPTNO >=", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLessThan(String value) {
            addCriterion("RPTNO <", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLessThanOrEqualTo(String value) {
            addCriterion("RPTNO <=", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLike(String value) {
            addCriterion("RPTNO like", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotLike(String value) {
            addCriterion("RPTNO not like", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoIn(List<String> values) {
            addCriterion("RPTNO in", values, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotIn(List<String> values) {
            addCriterion("RPTNO not in", values, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoBetween(String value1, String value2) {
            addCriterion("RPTNO between", value1, value2, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotBetween(String value1, String value2) {
            addCriterion("RPTNO not between", value1, value2, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnameIsNull() {
            addCriterion("RPTNAME is null");
            return (Criteria) this;
        }

        public Criteria andRptnameIsNotNull() {
            addCriterion("RPTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andRptnameEqualTo(String value) {
            addCriterion("RPTNAME =", value, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameNotEqualTo(String value) {
            addCriterion("RPTNAME <>", value, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameGreaterThan(String value) {
            addCriterion("RPTNAME >", value, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameGreaterThanOrEqualTo(String value) {
            addCriterion("RPTNAME >=", value, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameLessThan(String value) {
            addCriterion("RPTNAME <", value, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameLessThanOrEqualTo(String value) {
            addCriterion("RPTNAME <=", value, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameLike(String value) {
            addCriterion("RPTNAME like", value, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameNotLike(String value) {
            addCriterion("RPTNAME not like", value, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameIn(List<String> values) {
            addCriterion("RPTNAME in", values, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameNotIn(List<String> values) {
            addCriterion("RPTNAME not in", values, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameBetween(String value1, String value2) {
            addCriterion("RPTNAME between", value1, value2, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptnameNotBetween(String value1, String value2) {
            addCriterion("RPTNAME not between", value1, value2, "rptname");
            return (Criteria) this;
        }

        public Criteria andRptdescIsNull() {
            addCriterion("RPTDESC is null");
            return (Criteria) this;
        }

        public Criteria andRptdescIsNotNull() {
            addCriterion("RPTDESC is not null");
            return (Criteria) this;
        }

        public Criteria andRptdescEqualTo(String value) {
            addCriterion("RPTDESC =", value, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescNotEqualTo(String value) {
            addCriterion("RPTDESC <>", value, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescGreaterThan(String value) {
            addCriterion("RPTDESC >", value, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescGreaterThanOrEqualTo(String value) {
            addCriterion("RPTDESC >=", value, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescLessThan(String value) {
            addCriterion("RPTDESC <", value, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescLessThanOrEqualTo(String value) {
            addCriterion("RPTDESC <=", value, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescLike(String value) {
            addCriterion("RPTDESC like", value, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescNotLike(String value) {
            addCriterion("RPTDESC not like", value, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescIn(List<String> values) {
            addCriterion("RPTDESC in", values, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescNotIn(List<String> values) {
            addCriterion("RPTDESC not in", values, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescBetween(String value1, String value2) {
            addCriterion("RPTDESC between", value1, value2, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRptdescNotBetween(String value1, String value2) {
            addCriterion("RPTDESC not between", value1, value2, "rptdesc");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("STARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("STARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(String value) {
            addCriterion("STARTDATE =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(String value) {
            addCriterion("STARTDATE <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(String value) {
            addCriterion("STARTDATE >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("STARTDATE >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(String value) {
            addCriterion("STARTDATE <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(String value) {
            addCriterion("STARTDATE <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLike(String value) {
            addCriterion("STARTDATE like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotLike(String value) {
            addCriterion("STARTDATE not like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<String> values) {
            addCriterion("STARTDATE in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<String> values) {
            addCriterion("STARTDATE not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(String value1, String value2) {
            addCriterion("STARTDATE between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(String value1, String value2) {
            addCriterion("STARTDATE not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("ENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("ENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(String value) {
            addCriterion("ENDDATE =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(String value) {
            addCriterion("ENDDATE <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(String value) {
            addCriterion("ENDDATE >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(String value) {
            addCriterion("ENDDATE >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(String value) {
            addCriterion("ENDDATE <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(String value) {
            addCriterion("ENDDATE <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLike(String value) {
            addCriterion("ENDDATE like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotLike(String value) {
            addCriterion("ENDDATE not like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<String> values) {
            addCriterion("ENDDATE in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<String> values) {
            addCriterion("ENDDATE not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(String value1, String value2) {
            addCriterion("ENDDATE between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(String value1, String value2) {
            addCriterion("ENDDATE not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andImpdateIsNull() {
            addCriterion("IMPDATE is null");
            return (Criteria) this;
        }

        public Criteria andImpdateIsNotNull() {
            addCriterion("IMPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andImpdateEqualTo(String value) {
            addCriterion("IMPDATE =", value, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateNotEqualTo(String value) {
            addCriterion("IMPDATE <>", value, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateGreaterThan(String value) {
            addCriterion("IMPDATE >", value, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateGreaterThanOrEqualTo(String value) {
            addCriterion("IMPDATE >=", value, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateLessThan(String value) {
            addCriterion("IMPDATE <", value, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateLessThanOrEqualTo(String value) {
            addCriterion("IMPDATE <=", value, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateLike(String value) {
            addCriterion("IMPDATE like", value, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateNotLike(String value) {
            addCriterion("IMPDATE not like", value, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateIn(List<String> values) {
            addCriterion("IMPDATE in", values, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateNotIn(List<String> values) {
            addCriterion("IMPDATE not in", values, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateBetween(String value1, String value2) {
            addCriterion("IMPDATE between", value1, value2, "impdate");
            return (Criteria) this;
        }

        public Criteria andImpdateNotBetween(String value1, String value2) {
            addCriterion("IMPDATE not between", value1, value2, "impdate");
            return (Criteria) this;
        }

        public Criteria andRecverIsNull() {
            addCriterion("RECVER is null");
            return (Criteria) this;
        }

        public Criteria andRecverIsNotNull() {
            addCriterion("RECVER is not null");
            return (Criteria) this;
        }

        public Criteria andRecverEqualTo(Integer value) {
            addCriterion("RECVER =", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverNotEqualTo(Integer value) {
            addCriterion("RECVER <>", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverGreaterThan(Integer value) {
            addCriterion("RECVER >", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECVER >=", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverLessThan(Integer value) {
            addCriterion("RECVER <", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverLessThanOrEqualTo(Integer value) {
            addCriterion("RECVER <=", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverIn(List<Integer> values) {
            addCriterion("RECVER in", values, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverNotIn(List<Integer> values) {
            addCriterion("RECVER not in", values, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverBetween(Integer value1, Integer value2) {
            addCriterion("RECVER between", value1, value2, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverNotBetween(Integer value1, Integer value2) {
            addCriterion("RECVER not between", value1, value2, "recver");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 11 17:46:05 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CLS_UD_TBLINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}