package pams.repository.model;

import java.util.ArrayList;
import java.util.List;

public class ClsUdFldinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public ClsUdFldinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFldsnIsNull() {
            addCriterion("FLDSN is null");
            return (Criteria) this;
        }

        public Criteria andFldsnIsNotNull() {
            addCriterion("FLDSN is not null");
            return (Criteria) this;
        }

        public Criteria andFldsnEqualTo(String value) {
            addCriterion("FLDSN =", value, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnNotEqualTo(String value) {
            addCriterion("FLDSN <>", value, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnGreaterThan(String value) {
            addCriterion("FLDSN >", value, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnGreaterThanOrEqualTo(String value) {
            addCriterion("FLDSN >=", value, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnLessThan(String value) {
            addCriterion("FLDSN <", value, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnLessThanOrEqualTo(String value) {
            addCriterion("FLDSN <=", value, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnLike(String value) {
            addCriterion("FLDSN like", value, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnNotLike(String value) {
            addCriterion("FLDSN not like", value, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnIn(List<String> values) {
            addCriterion("FLDSN in", values, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnNotIn(List<String> values) {
            addCriterion("FLDSN not in", values, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnBetween(String value1, String value2) {
            addCriterion("FLDSN between", value1, value2, "fldsn");
            return (Criteria) this;
        }

        public Criteria andFldsnNotBetween(String value1, String value2) {
            addCriterion("FLDSN not between", value1, value2, "fldsn");
            return (Criteria) this;
        }

        public Criteria andRptnoIsNull() {
            addCriterion("RPTNO is null");
            return (Criteria) this;
        }

        public Criteria andRptnoIsNotNull() {
            addCriterion("RPTNO is not null");
            return (Criteria) this;
        }

        public Criteria andRptnoEqualTo(String value) {
            addCriterion("RPTNO =", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotEqualTo(String value) {
            addCriterion("RPTNO <>", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoGreaterThan(String value) {
            addCriterion("RPTNO >", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoGreaterThanOrEqualTo(String value) {
            addCriterion("RPTNO >=", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLessThan(String value) {
            addCriterion("RPTNO <", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLessThanOrEqualTo(String value) {
            addCriterion("RPTNO <=", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLike(String value) {
            addCriterion("RPTNO like", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotLike(String value) {
            addCriterion("RPTNO not like", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoIn(List<String> values) {
            addCriterion("RPTNO in", values, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotIn(List<String> values) {
            addCriterion("RPTNO not in", values, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoBetween(String value1, String value2) {
            addCriterion("RPTNO between", value1, value2, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotBetween(String value1, String value2) {
            addCriterion("RPTNO not between", value1, value2, "rptno");
            return (Criteria) this;
        }

        public Criteria andFldnameIsNull() {
            addCriterion("FLDNAME is null");
            return (Criteria) this;
        }

        public Criteria andFldnameIsNotNull() {
            addCriterion("FLDNAME is not null");
            return (Criteria) this;
        }

        public Criteria andFldnameEqualTo(String value) {
            addCriterion("FLDNAME =", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameNotEqualTo(String value) {
            addCriterion("FLDNAME <>", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameGreaterThan(String value) {
            addCriterion("FLDNAME >", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameGreaterThanOrEqualTo(String value) {
            addCriterion("FLDNAME >=", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameLessThan(String value) {
            addCriterion("FLDNAME <", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameLessThanOrEqualTo(String value) {
            addCriterion("FLDNAME <=", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameLike(String value) {
            addCriterion("FLDNAME like", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameNotLike(String value) {
            addCriterion("FLDNAME not like", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameIn(List<String> values) {
            addCriterion("FLDNAME in", values, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameNotIn(List<String> values) {
            addCriterion("FLDNAME not in", values, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameBetween(String value1, String value2) {
            addCriterion("FLDNAME between", value1, value2, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameNotBetween(String value1, String value2) {
            addCriterion("FLDNAME not between", value1, value2, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldtypeIsNull() {
            addCriterion("FLDTYPE is null");
            return (Criteria) this;
        }

        public Criteria andFldtypeIsNotNull() {
            addCriterion("FLDTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFldtypeEqualTo(String value) {
            addCriterion("FLDTYPE =", value, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeNotEqualTo(String value) {
            addCriterion("FLDTYPE <>", value, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeGreaterThan(String value) {
            addCriterion("FLDTYPE >", value, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeGreaterThanOrEqualTo(String value) {
            addCriterion("FLDTYPE >=", value, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeLessThan(String value) {
            addCriterion("FLDTYPE <", value, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeLessThanOrEqualTo(String value) {
            addCriterion("FLDTYPE <=", value, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeLike(String value) {
            addCriterion("FLDTYPE like", value, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeNotLike(String value) {
            addCriterion("FLDTYPE not like", value, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeIn(List<String> values) {
            addCriterion("FLDTYPE in", values, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeNotIn(List<String> values) {
            addCriterion("FLDTYPE not in", values, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeBetween(String value1, String value2) {
            addCriterion("FLDTYPE between", value1, value2, "fldtype");
            return (Criteria) this;
        }

        public Criteria andFldtypeNotBetween(String value1, String value2) {
            addCriterion("FLDTYPE not between", value1, value2, "fldtype");
            return (Criteria) this;
        }

        public Criteria andRecverIsNull() {
            addCriterion("RECVER is null");
            return (Criteria) this;
        }

        public Criteria andRecverIsNotNull() {
            addCriterion("RECVER is not null");
            return (Criteria) this;
        }

        public Criteria andRecverEqualTo(Integer value) {
            addCriterion("RECVER =", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverNotEqualTo(Integer value) {
            addCriterion("RECVER <>", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverGreaterThan(Integer value) {
            addCriterion("RECVER >", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECVER >=", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverLessThan(Integer value) {
            addCriterion("RECVER <", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverLessThanOrEqualTo(Integer value) {
            addCriterion("RECVER <=", value, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverIn(List<Integer> values) {
            addCriterion("RECVER in", values, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverNotIn(List<Integer> values) {
            addCriterion("RECVER not in", values, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverBetween(Integer value1, Integer value2) {
            addCriterion("RECVER between", value1, value2, "recver");
            return (Criteria) this;
        }

        public Criteria andRecverNotBetween(Integer value1, Integer value2) {
            addCriterion("RECVER not between", value1, value2, "recver");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 11 17:46:05 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CLS_UD_FLDINFO
     *
     * @mbggenerated Fri Apr 11 17:46:05 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}