package pams.repository.model;

public class ClsUdTblinfo extends ClsUdTblinfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_TBLINFO.RPTNAME
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    private String rptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_TBLINFO.RPTDESC
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    private String rptdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_TBLINFO.REMARK
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_TBLINFO.STATUS
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_TBLINFO.STARTDATE
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    private String startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_TBLINFO.ENDDATE
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    private String enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_TBLINFO.IMPDATE
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    private String impdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLS_UD_TBLINFO.RECVER
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    private Integer recver;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_TBLINFO.RPTNAME
     *
     * @return the value of CLS_UD_TBLINFO.RPTNAME
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public String getRptname() {
        return rptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_TBLINFO.RPTNAME
     *
     * @param rptname the value for CLS_UD_TBLINFO.RPTNAME
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public void setRptname(String rptname) {
        this.rptname = rptname == null ? null : rptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_TBLINFO.RPTDESC
     *
     * @return the value of CLS_UD_TBLINFO.RPTDESC
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public String getRptdesc() {
        return rptdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_TBLINFO.RPTDESC
     *
     * @param rptdesc the value for CLS_UD_TBLINFO.RPTDESC
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public void setRptdesc(String rptdesc) {
        this.rptdesc = rptdesc == null ? null : rptdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_TBLINFO.REMARK
     *
     * @return the value of CLS_UD_TBLINFO.REMARK
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_TBLINFO.REMARK
     *
     * @param remark the value for CLS_UD_TBLINFO.REMARK
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_TBLINFO.STATUS
     *
     * @return the value of CLS_UD_TBLINFO.STATUS
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_TBLINFO.STATUS
     *
     * @param status the value for CLS_UD_TBLINFO.STATUS
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_TBLINFO.STARTDATE
     *
     * @return the value of CLS_UD_TBLINFO.STARTDATE
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_TBLINFO.STARTDATE
     *
     * @param startdate the value for CLS_UD_TBLINFO.STARTDATE
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_TBLINFO.ENDDATE
     *
     * @return the value of CLS_UD_TBLINFO.ENDDATE
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_TBLINFO.ENDDATE
     *
     * @param enddate the value for CLS_UD_TBLINFO.ENDDATE
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate == null ? null : enddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_TBLINFO.IMPDATE
     *
     * @return the value of CLS_UD_TBLINFO.IMPDATE
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public String getImpdate() {
        return impdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_TBLINFO.IMPDATE
     *
     * @param impdate the value for CLS_UD_TBLINFO.IMPDATE
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public void setImpdate(String impdate) {
        this.impdate = impdate == null ? null : impdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLS_UD_TBLINFO.RECVER
     *
     * @return the value of CLS_UD_TBLINFO.RECVER
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public Integer getRecver() {
        return recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLS_UD_TBLINFO.RECVER
     *
     * @param recver the value for CLS_UD_TBLINFO.RECVER
     *
     * @mbggenerated Sun May 24 14:39:48 CST 2015
     */
    public void setRecver(Integer recver) {
        this.recver = recver;
    }
}