package pams.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OdsbPayagentTxnExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public OdsbPayagentTxnExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGuidIsNull() {
            addCriterion("GUID is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("GUID is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("GUID =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("GUID <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("GUID >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("GUID >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("GUID <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("GUID <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("GUID like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("GUID not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("GUID in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("GUID not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("GUID between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("GUID not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andAcctNameIsNull() {
            addCriterion("ACCT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAcctNameIsNotNull() {
            addCriterion("ACCT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAcctNameEqualTo(String value) {
            addCriterion("ACCT_NAME =", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameNotEqualTo(String value) {
            addCriterion("ACCT_NAME <>", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameGreaterThan(String value) {
            addCriterion("ACCT_NAME >", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_NAME >=", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameLessThan(String value) {
            addCriterion("ACCT_NAME <", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameLessThanOrEqualTo(String value) {
            addCriterion("ACCT_NAME <=", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameLike(String value) {
            addCriterion("ACCT_NAME like", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameNotLike(String value) {
            addCriterion("ACCT_NAME not like", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameIn(List<String> values) {
            addCriterion("ACCT_NAME in", values, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameNotIn(List<String> values) {
            addCriterion("ACCT_NAME not in", values, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameBetween(String value1, String value2) {
            addCriterion("ACCT_NAME between", value1, value2, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameNotBetween(String value1, String value2) {
            addCriterion("ACCT_NAME not between", value1, value2, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNoIsNull() {
            addCriterion("ACCT_NO is null");
            return (Criteria) this;
        }

        public Criteria andAcctNoIsNotNull() {
            addCriterion("ACCT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAcctNoEqualTo(String value) {
            addCriterion("ACCT_NO =", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotEqualTo(String value) {
            addCriterion("ACCT_NO <>", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoGreaterThan(String value) {
            addCriterion("ACCT_NO >", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_NO >=", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoLessThan(String value) {
            addCriterion("ACCT_NO <", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoLessThanOrEqualTo(String value) {
            addCriterion("ACCT_NO <=", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoLike(String value) {
            addCriterion("ACCT_NO like", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotLike(String value) {
            addCriterion("ACCT_NO not like", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoIn(List<String> values) {
            addCriterion("ACCT_NO in", values, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotIn(List<String> values) {
            addCriterion("ACCT_NO not in", values, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoBetween(String value1, String value2) {
            addCriterion("ACCT_NO between", value1, value2, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotBetween(String value1, String value2) {
            addCriterion("ACCT_NO not between", value1, value2, "acctNo");
            return (Criteria) this;
        }

        public Criteria andInstNoIsNull() {
            addCriterion("INST_NO is null");
            return (Criteria) this;
        }

        public Criteria andInstNoIsNotNull() {
            addCriterion("INST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andInstNoEqualTo(String value) {
            addCriterion("INST_NO =", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoNotEqualTo(String value) {
            addCriterion("INST_NO <>", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoGreaterThan(String value) {
            addCriterion("INST_NO >", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoGreaterThanOrEqualTo(String value) {
            addCriterion("INST_NO >=", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoLessThan(String value) {
            addCriterion("INST_NO <", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoLessThanOrEqualTo(String value) {
            addCriterion("INST_NO <=", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoLike(String value) {
            addCriterion("INST_NO like", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoNotLike(String value) {
            addCriterion("INST_NO not like", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoIn(List<String> values) {
            addCriterion("INST_NO in", values, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoNotIn(List<String> values) {
            addCriterion("INST_NO not in", values, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoBetween(String value1, String value2) {
            addCriterion("INST_NO between", value1, value2, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoNotBetween(String value1, String value2) {
            addCriterion("INST_NO not between", value1, value2, "instNo");
            return (Criteria) this;
        }

        public Criteria andAcctName1IsNull() {
            addCriterion("ACCT_NAME1 is null");
            return (Criteria) this;
        }

        public Criteria andAcctName1IsNotNull() {
            addCriterion("ACCT_NAME1 is not null");
            return (Criteria) this;
        }

        public Criteria andAcctName1EqualTo(String value) {
            addCriterion("ACCT_NAME1 =", value, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1NotEqualTo(String value) {
            addCriterion("ACCT_NAME1 <>", value, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1GreaterThan(String value) {
            addCriterion("ACCT_NAME1 >", value, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1GreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_NAME1 >=", value, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1LessThan(String value) {
            addCriterion("ACCT_NAME1 <", value, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1LessThanOrEqualTo(String value) {
            addCriterion("ACCT_NAME1 <=", value, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1Like(String value) {
            addCriterion("ACCT_NAME1 like", value, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1NotLike(String value) {
            addCriterion("ACCT_NAME1 not like", value, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1In(List<String> values) {
            addCriterion("ACCT_NAME1 in", values, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1NotIn(List<String> values) {
            addCriterion("ACCT_NAME1 not in", values, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1Between(String value1, String value2) {
            addCriterion("ACCT_NAME1 between", value1, value2, "acctName1");
            return (Criteria) this;
        }

        public Criteria andAcctName1NotBetween(String value1, String value2) {
            addCriterion("ACCT_NAME1 not between", value1, value2, "acctName1");
            return (Criteria) this;
        }

        public Criteria andSignInstnIsNull() {
            addCriterion("SIGN_INSTN is null");
            return (Criteria) this;
        }

        public Criteria andSignInstnIsNotNull() {
            addCriterion("SIGN_INSTN is not null");
            return (Criteria) this;
        }

        public Criteria andSignInstnEqualTo(String value) {
            addCriterion("SIGN_INSTN =", value, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnNotEqualTo(String value) {
            addCriterion("SIGN_INSTN <>", value, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnGreaterThan(String value) {
            addCriterion("SIGN_INSTN >", value, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnGreaterThanOrEqualTo(String value) {
            addCriterion("SIGN_INSTN >=", value, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnLessThan(String value) {
            addCriterion("SIGN_INSTN <", value, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnLessThanOrEqualTo(String value) {
            addCriterion("SIGN_INSTN <=", value, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnLike(String value) {
            addCriterion("SIGN_INSTN like", value, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnNotLike(String value) {
            addCriterion("SIGN_INSTN not like", value, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnIn(List<String> values) {
            addCriterion("SIGN_INSTN in", values, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnNotIn(List<String> values) {
            addCriterion("SIGN_INSTN not in", values, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnBetween(String value1, String value2) {
            addCriterion("SIGN_INSTN between", value1, value2, "signInstn");
            return (Criteria) this;
        }

        public Criteria andSignInstnNotBetween(String value1, String value2) {
            addCriterion("SIGN_INSTN not between", value1, value2, "signInstn");
            return (Criteria) this;
        }

        public Criteria andChnNoIsNull() {
            addCriterion("CHN_NO is null");
            return (Criteria) this;
        }

        public Criteria andChnNoIsNotNull() {
            addCriterion("CHN_NO is not null");
            return (Criteria) this;
        }

        public Criteria andChnNoEqualTo(String value) {
            addCriterion("CHN_NO =", value, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoNotEqualTo(String value) {
            addCriterion("CHN_NO <>", value, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoGreaterThan(String value) {
            addCriterion("CHN_NO >", value, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoGreaterThanOrEqualTo(String value) {
            addCriterion("CHN_NO >=", value, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoLessThan(String value) {
            addCriterion("CHN_NO <", value, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoLessThanOrEqualTo(String value) {
            addCriterion("CHN_NO <=", value, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoLike(String value) {
            addCriterion("CHN_NO like", value, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoNotLike(String value) {
            addCriterion("CHN_NO not like", value, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoIn(List<String> values) {
            addCriterion("CHN_NO in", values, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoNotIn(List<String> values) {
            addCriterion("CHN_NO not in", values, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoBetween(String value1, String value2) {
            addCriterion("CHN_NO between", value1, value2, "chnNo");
            return (Criteria) this;
        }

        public Criteria andChnNoNotBetween(String value1, String value2) {
            addCriterion("CHN_NO not between", value1, value2, "chnNo");
            return (Criteria) this;
        }

        public Criteria andAcctNo1IsNull() {
            addCriterion("ACCT_NO1 is null");
            return (Criteria) this;
        }

        public Criteria andAcctNo1IsNotNull() {
            addCriterion("ACCT_NO1 is not null");
            return (Criteria) this;
        }

        public Criteria andAcctNo1EqualTo(String value) {
            addCriterion("ACCT_NO1 =", value, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1NotEqualTo(String value) {
            addCriterion("ACCT_NO1 <>", value, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1GreaterThan(String value) {
            addCriterion("ACCT_NO1 >", value, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1GreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_NO1 >=", value, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1LessThan(String value) {
            addCriterion("ACCT_NO1 <", value, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1LessThanOrEqualTo(String value) {
            addCriterion("ACCT_NO1 <=", value, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1Like(String value) {
            addCriterion("ACCT_NO1 like", value, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1NotLike(String value) {
            addCriterion("ACCT_NO1 not like", value, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1In(List<String> values) {
            addCriterion("ACCT_NO1 in", values, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1NotIn(List<String> values) {
            addCriterion("ACCT_NO1 not in", values, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1Between(String value1, String value2) {
            addCriterion("ACCT_NO1 between", value1, value2, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andAcctNo1NotBetween(String value1, String value2) {
            addCriterion("ACCT_NO1 not between", value1, value2, "acctNo1");
            return (Criteria) this;
        }

        public Criteria andChnCustNoIsNull() {
            addCriterion("CHN_CUST_NO is null");
            return (Criteria) this;
        }

        public Criteria andChnCustNoIsNotNull() {
            addCriterion("CHN_CUST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andChnCustNoEqualTo(String value) {
            addCriterion("CHN_CUST_NO =", value, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoNotEqualTo(String value) {
            addCriterion("CHN_CUST_NO <>", value, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoGreaterThan(String value) {
            addCriterion("CHN_CUST_NO >", value, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoGreaterThanOrEqualTo(String value) {
            addCriterion("CHN_CUST_NO >=", value, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoLessThan(String value) {
            addCriterion("CHN_CUST_NO <", value, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoLessThanOrEqualTo(String value) {
            addCriterion("CHN_CUST_NO <=", value, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoLike(String value) {
            addCriterion("CHN_CUST_NO like", value, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoNotLike(String value) {
            addCriterion("CHN_CUST_NO not like", value, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoIn(List<String> values) {
            addCriterion("CHN_CUST_NO in", values, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoNotIn(List<String> values) {
            addCriterion("CHN_CUST_NO not in", values, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoBetween(String value1, String value2) {
            addCriterion("CHN_CUST_NO between", value1, value2, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andChnCustNoNotBetween(String value1, String value2) {
            addCriterion("CHN_CUST_NO not between", value1, value2, "chnCustNo");
            return (Criteria) this;
        }

        public Criteria andAgBscExpIsNull() {
            addCriterion("AG_BSC_EXP is null");
            return (Criteria) this;
        }

        public Criteria andAgBscExpIsNotNull() {
            addCriterion("AG_BSC_EXP is not null");
            return (Criteria) this;
        }

        public Criteria andAgBscExpEqualTo(BigDecimal value) {
            addCriterion("AG_BSC_EXP =", value, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andAgBscExpNotEqualTo(BigDecimal value) {
            addCriterion("AG_BSC_EXP <>", value, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andAgBscExpGreaterThan(BigDecimal value) {
            addCriterion("AG_BSC_EXP >", value, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andAgBscExpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AG_BSC_EXP >=", value, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andAgBscExpLessThan(BigDecimal value) {
            addCriterion("AG_BSC_EXP <", value, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andAgBscExpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AG_BSC_EXP <=", value, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andAgBscExpIn(List<BigDecimal> values) {
            addCriterion("AG_BSC_EXP in", values, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andAgBscExpNotIn(List<BigDecimal> values) {
            addCriterion("AG_BSC_EXP not in", values, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andAgBscExpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AG_BSC_EXP between", value1, value2, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andAgBscExpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AG_BSC_EXP not between", value1, value2, "agBscExp");
            return (Criteria) this;
        }

        public Criteria andCrTxDtIsNull() {
            addCriterion("CR_TX_DT is null");
            return (Criteria) this;
        }

        public Criteria andCrTxDtIsNotNull() {
            addCriterion("CR_TX_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCrTxDtEqualTo(String value) {
            addCriterion("CR_TX_DT =", value, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtNotEqualTo(String value) {
            addCriterion("CR_TX_DT <>", value, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtGreaterThan(String value) {
            addCriterion("CR_TX_DT >", value, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtGreaterThanOrEqualTo(String value) {
            addCriterion("CR_TX_DT >=", value, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtLessThan(String value) {
            addCriterion("CR_TX_DT <", value, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtLessThanOrEqualTo(String value) {
            addCriterion("CR_TX_DT <=", value, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtLike(String value) {
            addCriterion("CR_TX_DT like", value, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtNotLike(String value) {
            addCriterion("CR_TX_DT not like", value, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtIn(List<String> values) {
            addCriterion("CR_TX_DT in", values, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtNotIn(List<String> values) {
            addCriterion("CR_TX_DT not in", values, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtBetween(String value1, String value2) {
            addCriterion("CR_TX_DT between", value1, value2, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCrTxDtNotBetween(String value1, String value2) {
            addCriterion("CR_TX_DT not between", value1, value2, "crTxDt");
            return (Criteria) this;
        }

        public Criteria andCustNoIsNull() {
            addCriterion("CUST_NO is null");
            return (Criteria) this;
        }

        public Criteria andCustNoIsNotNull() {
            addCriterion("CUST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCustNoEqualTo(String value) {
            addCriterion("CUST_NO =", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotEqualTo(String value) {
            addCriterion("CUST_NO <>", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThan(String value) {
            addCriterion("CUST_NO >", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NO >=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThan(String value) {
            addCriterion("CUST_NO <", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThanOrEqualTo(String value) {
            addCriterion("CUST_NO <=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLike(String value) {
            addCriterion("CUST_NO like", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotLike(String value) {
            addCriterion("CUST_NO not like", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoIn(List<String> values) {
            addCriterion("CUST_NO in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotIn(List<String> values) {
            addCriterion("CUST_NO not in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoBetween(String value1, String value2) {
            addCriterion("CUST_NO between", value1, value2, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotBetween(String value1, String value2) {
            addCriterion("CUST_NO not between", value1, value2, "custNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 06 21:14:35 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ODSB_PAYAGENT_TXN
     *
     * @mbggenerated Mon Jan 06 21:14:35 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}