package pams.repository.model;

public class OdsbPldfBatchKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_PLDF_BATCH.ACCT_NO
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    private String acctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_PLDF_BATCH.CHANL_FLOW_NO
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    private String chanlFlowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_PLDF_BATCH.CR_TX_DT
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    private String crTxDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_PLDF_BATCH.ACCT_NO
     *
     * @return the value of ODSB_PLDF_BATCH.ACCT_NO
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_PLDF_BATCH.ACCT_NO
     *
     * @param acctNo the value for ODSB_PLDF_BATCH.ACCT_NO
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_PLDF_BATCH.CHANL_FLOW_NO
     *
     * @return the value of ODSB_PLDF_BATCH.CHANL_FLOW_NO
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    public String getChanlFlowNo() {
        return chanlFlowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_PLDF_BATCH.CHANL_FLOW_NO
     *
     * @param chanlFlowNo the value for ODSB_PLDF_BATCH.CHANL_FLOW_NO
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    public void setChanlFlowNo(String chanlFlowNo) {
        this.chanlFlowNo = chanlFlowNo == null ? null : chanlFlowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_PLDF_BATCH.CR_TX_DT
     *
     * @return the value of ODSB_PLDF_BATCH.CR_TX_DT
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    public String getCrTxDt() {
        return crTxDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_PLDF_BATCH.CR_TX_DT
     *
     * @param crTxDt the value for ODSB_PLDF_BATCH.CR_TX_DT
     *
     * @mbggenerated Sun Mar 01 19:22:27 CST 2015
     */
    public void setCrTxDt(String crTxDt) {
        this.crTxDt = crTxDt == null ? null : crTxDt.trim();
    }
}