package pams.repository.model;

import java.math.BigDecimal;

public class OdsbHousingfundTxn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_HOUSINGFUND_TXN.INST_NO
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    private String instNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_HOUSINGFUND_TXN.INST_NAME
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    private String instName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_HOUSINGFUND_TXN.CUST_NAME
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_HOUSINGFUND_TXN.CRD_NO
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    private String crdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_HOUSINGFUND_TXN.AMT
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    private BigDecimal amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_HOUSINGFUND_TXN.INSTN_NO
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    private String instnNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_HOUSINGFUND_TXN.INSTN_NAME
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    private String instnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_HOUSINGFUND_TXN.NO_BODY1
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    private String noBody1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ODSB_HOUSINGFUND_TXN.GUID
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    private String guid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_HOUSINGFUND_TXN.INST_NO
     *
     * @return the value of ODSB_HOUSINGFUND_TXN.INST_NO
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public String getInstNo() {
        return instNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_HOUSINGFUND_TXN.INST_NO
     *
     * @param instNo the value for ODSB_HOUSINGFUND_TXN.INST_NO
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public void setInstNo(String instNo) {
        this.instNo = instNo == null ? null : instNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_HOUSINGFUND_TXN.INST_NAME
     *
     * @return the value of ODSB_HOUSINGFUND_TXN.INST_NAME
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public String getInstName() {
        return instName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_HOUSINGFUND_TXN.INST_NAME
     *
     * @param instName the value for ODSB_HOUSINGFUND_TXN.INST_NAME
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public void setInstName(String instName) {
        this.instName = instName == null ? null : instName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_HOUSINGFUND_TXN.CUST_NAME
     *
     * @return the value of ODSB_HOUSINGFUND_TXN.CUST_NAME
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_HOUSINGFUND_TXN.CUST_NAME
     *
     * @param custName the value for ODSB_HOUSINGFUND_TXN.CUST_NAME
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_HOUSINGFUND_TXN.CRD_NO
     *
     * @return the value of ODSB_HOUSINGFUND_TXN.CRD_NO
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public String getCrdNo() {
        return crdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_HOUSINGFUND_TXN.CRD_NO
     *
     * @param crdNo the value for ODSB_HOUSINGFUND_TXN.CRD_NO
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public void setCrdNo(String crdNo) {
        this.crdNo = crdNo == null ? null : crdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_HOUSINGFUND_TXN.AMT
     *
     * @return the value of ODSB_HOUSINGFUND_TXN.AMT
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_HOUSINGFUND_TXN.AMT
     *
     * @param amt the value for ODSB_HOUSINGFUND_TXN.AMT
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_HOUSINGFUND_TXN.INSTN_NO
     *
     * @return the value of ODSB_HOUSINGFUND_TXN.INSTN_NO
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public String getInstnNo() {
        return instnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_HOUSINGFUND_TXN.INSTN_NO
     *
     * @param instnNo the value for ODSB_HOUSINGFUND_TXN.INSTN_NO
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public void setInstnNo(String instnNo) {
        this.instnNo = instnNo == null ? null : instnNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_HOUSINGFUND_TXN.INSTN_NAME
     *
     * @return the value of ODSB_HOUSINGFUND_TXN.INSTN_NAME
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public String getInstnName() {
        return instnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_HOUSINGFUND_TXN.INSTN_NAME
     *
     * @param instnName the value for ODSB_HOUSINGFUND_TXN.INSTN_NAME
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public void setInstnName(String instnName) {
        this.instnName = instnName == null ? null : instnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_HOUSINGFUND_TXN.NO_BODY1
     *
     * @return the value of ODSB_HOUSINGFUND_TXN.NO_BODY1
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public String getNoBody1() {
        return noBody1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_HOUSINGFUND_TXN.NO_BODY1
     *
     * @param noBody1 the value for ODSB_HOUSINGFUND_TXN.NO_BODY1
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public void setNoBody1(String noBody1) {
        this.noBody1 = noBody1 == null ? null : noBody1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ODSB_HOUSINGFUND_TXN.GUID
     *
     * @return the value of ODSB_HOUSINGFUND_TXN.GUID
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ODSB_HOUSINGFUND_TXN.GUID
     *
     * @param guid the value for ODSB_HOUSINGFUND_TXN.GUID
     *
     * @mbggenerated Thu Mar 28 19:53:01 CST 2013
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }
}