package pams.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OdsbCtsBalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public OdsbCtsBalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGuidIsNull() {
            addCriterion("GUID is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("GUID is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("GUID =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("GUID <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("GUID >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("GUID >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("GUID <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("GUID <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("GUID like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("GUID not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("GUID in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("GUID not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("GUID between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("GUID not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andInstNameIsNull() {
            addCriterion("INST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andInstNameIsNotNull() {
            addCriterion("INST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andInstNameEqualTo(String value) {
            addCriterion("INST_NAME =", value, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameNotEqualTo(String value) {
            addCriterion("INST_NAME <>", value, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameGreaterThan(String value) {
            addCriterion("INST_NAME >", value, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameGreaterThanOrEqualTo(String value) {
            addCriterion("INST_NAME >=", value, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameLessThan(String value) {
            addCriterion("INST_NAME <", value, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameLessThanOrEqualTo(String value) {
            addCriterion("INST_NAME <=", value, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameLike(String value) {
            addCriterion("INST_NAME like", value, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameNotLike(String value) {
            addCriterion("INST_NAME not like", value, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameIn(List<String> values) {
            addCriterion("INST_NAME in", values, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameNotIn(List<String> values) {
            addCriterion("INST_NAME not in", values, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameBetween(String value1, String value2) {
            addCriterion("INST_NAME between", value1, value2, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNameNotBetween(String value1, String value2) {
            addCriterion("INST_NAME not between", value1, value2, "instName");
            return (Criteria) this;
        }

        public Criteria andInstNoIsNull() {
            addCriterion("INST_NO is null");
            return (Criteria) this;
        }

        public Criteria andInstNoIsNotNull() {
            addCriterion("INST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andInstNoEqualTo(String value) {
            addCriterion("INST_NO =", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoNotEqualTo(String value) {
            addCriterion("INST_NO <>", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoGreaterThan(String value) {
            addCriterion("INST_NO >", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoGreaterThanOrEqualTo(String value) {
            addCriterion("INST_NO >=", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoLessThan(String value) {
            addCriterion("INST_NO <", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoLessThanOrEqualTo(String value) {
            addCriterion("INST_NO <=", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoLike(String value) {
            addCriterion("INST_NO like", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoNotLike(String value) {
            addCriterion("INST_NO not like", value, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoIn(List<String> values) {
            addCriterion("INST_NO in", values, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoNotIn(List<String> values) {
            addCriterion("INST_NO not in", values, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoBetween(String value1, String value2) {
            addCriterion("INST_NO between", value1, value2, "instNo");
            return (Criteria) this;
        }

        public Criteria andInstNoNotBetween(String value1, String value2) {
            addCriterion("INST_NO not between", value1, value2, "instNo");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("CUST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("CUST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("CUST_NAME =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("CUST_NAME <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("CUST_NAME >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NAME >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("CUST_NAME <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("CUST_NAME <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("CUST_NAME like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("CUST_NAME not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("CUST_NAME in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("CUST_NAME not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("CUST_NAME between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("CUST_NAME not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNoIsNull() {
            addCriterion("CUST_NO is null");
            return (Criteria) this;
        }

        public Criteria andCustNoIsNotNull() {
            addCriterion("CUST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCustNoEqualTo(String value) {
            addCriterion("CUST_NO =", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotEqualTo(String value) {
            addCriterion("CUST_NO <>", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThan(String value) {
            addCriterion("CUST_NO >", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NO >=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThan(String value) {
            addCriterion("CUST_NO <", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThanOrEqualTo(String value) {
            addCriterion("CUST_NO <=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLike(String value) {
            addCriterion("CUST_NO like", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotLike(String value) {
            addCriterion("CUST_NO not like", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoIn(List<String> values) {
            addCriterion("CUST_NO in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotIn(List<String> values) {
            addCriterion("CUST_NO not in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoBetween(String value1, String value2) {
            addCriterion("CUST_NO between", value1, value2, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotBetween(String value1, String value2) {
            addCriterion("CUST_NO not between", value1, value2, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustPhoneIsNull() {
            addCriterion("CUST_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andCustPhoneIsNotNull() {
            addCriterion("CUST_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andCustPhoneEqualTo(String value) {
            addCriterion("CUST_PHONE =", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneNotEqualTo(String value) {
            addCriterion("CUST_PHONE <>", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneGreaterThan(String value) {
            addCriterion("CUST_PHONE >", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_PHONE >=", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneLessThan(String value) {
            addCriterion("CUST_PHONE <", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneLessThanOrEqualTo(String value) {
            addCriterion("CUST_PHONE <=", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneLike(String value) {
            addCriterion("CUST_PHONE like", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneNotLike(String value) {
            addCriterion("CUST_PHONE not like", value, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneIn(List<String> values) {
            addCriterion("CUST_PHONE in", values, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneNotIn(List<String> values) {
            addCriterion("CUST_PHONE not in", values, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneBetween(String value1, String value2) {
            addCriterion("CUST_PHONE between", value1, value2, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCustPhoneNotBetween(String value1, String value2) {
            addCriterion("CUST_PHONE not between", value1, value2, "custPhone");
            return (Criteria) this;
        }

        public Criteria andCtsBalIsNull() {
            addCriterion("CTS_BAL is null");
            return (Criteria) this;
        }

        public Criteria andCtsBalIsNotNull() {
            addCriterion("CTS_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andCtsBalEqualTo(BigDecimal value) {
            addCriterion("CTS_BAL =", value, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andCtsBalNotEqualTo(BigDecimal value) {
            addCriterion("CTS_BAL <>", value, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andCtsBalGreaterThan(BigDecimal value) {
            addCriterion("CTS_BAL >", value, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andCtsBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CTS_BAL >=", value, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andCtsBalLessThan(BigDecimal value) {
            addCriterion("CTS_BAL <", value, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andCtsBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CTS_BAL <=", value, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andCtsBalIn(List<BigDecimal> values) {
            addCriterion("CTS_BAL in", values, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andCtsBalNotIn(List<BigDecimal> values) {
            addCriterion("CTS_BAL not in", values, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andCtsBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CTS_BAL between", value1, value2, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andCtsBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CTS_BAL not between", value1, value2, "ctsBal");
            return (Criteria) this;
        }

        public Criteria andSignActnoIsNull() {
            addCriterion("SIGN_ACTNO is null");
            return (Criteria) this;
        }

        public Criteria andSignActnoIsNotNull() {
            addCriterion("SIGN_ACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andSignActnoEqualTo(String value) {
            addCriterion("SIGN_ACTNO =", value, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoNotEqualTo(String value) {
            addCriterion("SIGN_ACTNO <>", value, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoGreaterThan(String value) {
            addCriterion("SIGN_ACTNO >", value, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoGreaterThanOrEqualTo(String value) {
            addCriterion("SIGN_ACTNO >=", value, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoLessThan(String value) {
            addCriterion("SIGN_ACTNO <", value, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoLessThanOrEqualTo(String value) {
            addCriterion("SIGN_ACTNO <=", value, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoLike(String value) {
            addCriterion("SIGN_ACTNO like", value, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoNotLike(String value) {
            addCriterion("SIGN_ACTNO not like", value, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoIn(List<String> values) {
            addCriterion("SIGN_ACTNO in", values, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoNotIn(List<String> values) {
            addCriterion("SIGN_ACTNO not in", values, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoBetween(String value1, String value2) {
            addCriterion("SIGN_ACTNO between", value1, value2, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActnoNotBetween(String value1, String value2) {
            addCriterion("SIGN_ACTNO not between", value1, value2, "signActno");
            return (Criteria) this;
        }

        public Criteria andSignActBalIsNull() {
            addCriterion("SIGN_ACT_BAL is null");
            return (Criteria) this;
        }

        public Criteria andSignActBalIsNotNull() {
            addCriterion("SIGN_ACT_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andSignActBalEqualTo(BigDecimal value) {
            addCriterion("SIGN_ACT_BAL =", value, "signActBal");
            return (Criteria) this;
        }

        public Criteria andSignActBalNotEqualTo(BigDecimal value) {
            addCriterion("SIGN_ACT_BAL <>", value, "signActBal");
            return (Criteria) this;
        }

        public Criteria andSignActBalGreaterThan(BigDecimal value) {
            addCriterion("SIGN_ACT_BAL >", value, "signActBal");
            return (Criteria) this;
        }

        public Criteria andSignActBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SIGN_ACT_BAL >=", value, "signActBal");
            return (Criteria) this;
        }

        public Criteria andSignActBalLessThan(BigDecimal value) {
            addCriterion("SIGN_ACT_BAL <", value, "signActBal");
            return (Criteria) this;
        }

        public Criteria andSignActBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SIGN_ACT_BAL <=", value, "signActBal");
            return (Criteria) this;
        }

        public Criteria andSignActBalIn(List<BigDecimal> values) {
            addCriterion("SIGN_ACT_BAL in", values, "signActBal");
            return (Criteria) this;
        }

        public Criteria andSignActBalNotIn(List<BigDecimal> values) {
            addCriterion("SIGN_ACT_BAL not in", values, "signActBal");
            return (Criteria) this;
        }

        public Criteria andSignActBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SIGN_ACT_BAL between", value1, value2, "signActBal");
            return (Criteria) this;
        }

        public Criteria andSignActBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SIGN_ACT_BAL not between", value1, value2, "signActBal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 12 21:10:38 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ODSB_CTS_BAL
     *
     * @mbggenerated Sat Apr 12 21:10:38 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}