package pams.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OdsbStTconfirmTradExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public OdsbStTconfirmTradExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustNameIsNull() {
            addCriterion("CUST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("CUST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("CUST_NAME =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("CUST_NAME <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("CUST_NAME >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NAME >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("CUST_NAME <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("CUST_NAME <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("CUST_NAME like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("CUST_NAME not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("CUST_NAME in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("CUST_NAME not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("CUST_NAME between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("CUST_NAME not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCertNoIsNull() {
            addCriterion("CERT_NO is null");
            return (Criteria) this;
        }

        public Criteria andCertNoIsNotNull() {
            addCriterion("CERT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCertNoEqualTo(String value) {
            addCriterion("CERT_NO =", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotEqualTo(String value) {
            addCriterion("CERT_NO <>", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoGreaterThan(String value) {
            addCriterion("CERT_NO >", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoGreaterThanOrEqualTo(String value) {
            addCriterion("CERT_NO >=", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLessThan(String value) {
            addCriterion("CERT_NO <", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLessThanOrEqualTo(String value) {
            addCriterion("CERT_NO <=", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLike(String value) {
            addCriterion("CERT_NO like", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotLike(String value) {
            addCriterion("CERT_NO not like", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoIn(List<String> values) {
            addCriterion("CERT_NO in", values, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotIn(List<String> values) {
            addCriterion("CERT_NO not in", values, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoBetween(String value1, String value2) {
            addCriterion("CERT_NO between", value1, value2, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotBetween(String value1, String value2) {
            addCriterion("CERT_NO not between", value1, value2, "certNo");
            return (Criteria) this;
        }

        public Criteria andSecurCordIsNull() {
            addCriterion("SECUR_CORD is null");
            return (Criteria) this;
        }

        public Criteria andSecurCordIsNotNull() {
            addCriterion("SECUR_CORD is not null");
            return (Criteria) this;
        }

        public Criteria andSecurCordEqualTo(String value) {
            addCriterion("SECUR_CORD =", value, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordNotEqualTo(String value) {
            addCriterion("SECUR_CORD <>", value, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordGreaterThan(String value) {
            addCriterion("SECUR_CORD >", value, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordGreaterThanOrEqualTo(String value) {
            addCriterion("SECUR_CORD >=", value, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordLessThan(String value) {
            addCriterion("SECUR_CORD <", value, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordLessThanOrEqualTo(String value) {
            addCriterion("SECUR_CORD <=", value, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordLike(String value) {
            addCriterion("SECUR_CORD like", value, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordNotLike(String value) {
            addCriterion("SECUR_CORD not like", value, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordIn(List<String> values) {
            addCriterion("SECUR_CORD in", values, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordNotIn(List<String> values) {
            addCriterion("SECUR_CORD not in", values, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordBetween(String value1, String value2) {
            addCriterion("SECUR_CORD between", value1, value2, "securCord");
            return (Criteria) this;
        }

        public Criteria andSecurCordNotBetween(String value1, String value2) {
            addCriterion("SECUR_CORD not between", value1, value2, "securCord");
            return (Criteria) this;
        }

        public Criteria andCapiAccountIsNull() {
            addCriterion("CAPI_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andCapiAccountIsNotNull() {
            addCriterion("CAPI_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCapiAccountEqualTo(String value) {
            addCriterion("CAPI_ACCOUNT =", value, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountNotEqualTo(String value) {
            addCriterion("CAPI_ACCOUNT <>", value, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountGreaterThan(String value) {
            addCriterion("CAPI_ACCOUNT >", value, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountGreaterThanOrEqualTo(String value) {
            addCriterion("CAPI_ACCOUNT >=", value, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountLessThan(String value) {
            addCriterion("CAPI_ACCOUNT <", value, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountLessThanOrEqualTo(String value) {
            addCriterion("CAPI_ACCOUNT <=", value, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountLike(String value) {
            addCriterion("CAPI_ACCOUNT like", value, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountNotLike(String value) {
            addCriterion("CAPI_ACCOUNT not like", value, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountIn(List<String> values) {
            addCriterion("CAPI_ACCOUNT in", values, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountNotIn(List<String> values) {
            addCriterion("CAPI_ACCOUNT not in", values, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountBetween(String value1, String value2) {
            addCriterion("CAPI_ACCOUNT between", value1, value2, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andCapiAccountNotBetween(String value1, String value2) {
            addCriterion("CAPI_ACCOUNT not between", value1, value2, "capiAccount");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoIsNull() {
            addCriterion("FUND_ACCT_NO is null");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoIsNotNull() {
            addCriterion("FUND_ACCT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoEqualTo(String value) {
            addCriterion("FUND_ACCT_NO =", value, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoNotEqualTo(String value) {
            addCriterion("FUND_ACCT_NO <>", value, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoGreaterThan(String value) {
            addCriterion("FUND_ACCT_NO >", value, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("FUND_ACCT_NO >=", value, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoLessThan(String value) {
            addCriterion("FUND_ACCT_NO <", value, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoLessThanOrEqualTo(String value) {
            addCriterion("FUND_ACCT_NO <=", value, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoLike(String value) {
            addCriterion("FUND_ACCT_NO like", value, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoNotLike(String value) {
            addCriterion("FUND_ACCT_NO not like", value, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoIn(List<String> values) {
            addCriterion("FUND_ACCT_NO in", values, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoNotIn(List<String> values) {
            addCriterion("FUND_ACCT_NO not in", values, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoBetween(String value1, String value2) {
            addCriterion("FUND_ACCT_NO between", value1, value2, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundAcctNoNotBetween(String value1, String value2) {
            addCriterion("FUND_ACCT_NO not between", value1, value2, "fundAcctNo");
            return (Criteria) this;
        }

        public Criteria andFundCdIsNull() {
            addCriterion("FUND_CD is null");
            return (Criteria) this;
        }

        public Criteria andFundCdIsNotNull() {
            addCriterion("FUND_CD is not null");
            return (Criteria) this;
        }

        public Criteria andFundCdEqualTo(String value) {
            addCriterion("FUND_CD =", value, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdNotEqualTo(String value) {
            addCriterion("FUND_CD <>", value, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdGreaterThan(String value) {
            addCriterion("FUND_CD >", value, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdGreaterThanOrEqualTo(String value) {
            addCriterion("FUND_CD >=", value, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdLessThan(String value) {
            addCriterion("FUND_CD <", value, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdLessThanOrEqualTo(String value) {
            addCriterion("FUND_CD <=", value, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdLike(String value) {
            addCriterion("FUND_CD like", value, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdNotLike(String value) {
            addCriterion("FUND_CD not like", value, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdIn(List<String> values) {
            addCriterion("FUND_CD in", values, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdNotIn(List<String> values) {
            addCriterion("FUND_CD not in", values, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdBetween(String value1, String value2) {
            addCriterion("FUND_CD between", value1, value2, "fundCd");
            return (Criteria) this;
        }

        public Criteria andFundCdNotBetween(String value1, String value2) {
            addCriterion("FUND_CD not between", value1, value2, "fundCd");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntIsNull() {
            addCriterion("CUST_CITY_ACCNT is null");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntIsNotNull() {
            addCriterion("CUST_CITY_ACCNT is not null");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntEqualTo(String value) {
            addCriterion("CUST_CITY_ACCNT =", value, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntNotEqualTo(String value) {
            addCriterion("CUST_CITY_ACCNT <>", value, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntGreaterThan(String value) {
            addCriterion("CUST_CITY_ACCNT >", value, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_CITY_ACCNT >=", value, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntLessThan(String value) {
            addCriterion("CUST_CITY_ACCNT <", value, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntLessThanOrEqualTo(String value) {
            addCriterion("CUST_CITY_ACCNT <=", value, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntLike(String value) {
            addCriterion("CUST_CITY_ACCNT like", value, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntNotLike(String value) {
            addCriterion("CUST_CITY_ACCNT not like", value, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntIn(List<String> values) {
            addCriterion("CUST_CITY_ACCNT in", values, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntNotIn(List<String> values) {
            addCriterion("CUST_CITY_ACCNT not in", values, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntBetween(String value1, String value2) {
            addCriterion("CUST_CITY_ACCNT between", value1, value2, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andCustCityAccntNotBetween(String value1, String value2) {
            addCriterion("CUST_CITY_ACCNT not between", value1, value2, "custCityAccnt");
            return (Criteria) this;
        }

        public Criteria andDCdateIsNull() {
            addCriterion("D_CDATE is null");
            return (Criteria) this;
        }

        public Criteria andDCdateIsNotNull() {
            addCriterion("D_CDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDCdateEqualTo(String value) {
            addCriterion("D_CDATE =", value, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateNotEqualTo(String value) {
            addCriterion("D_CDATE <>", value, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateGreaterThan(String value) {
            addCriterion("D_CDATE >", value, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateGreaterThanOrEqualTo(String value) {
            addCriterion("D_CDATE >=", value, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateLessThan(String value) {
            addCriterion("D_CDATE <", value, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateLessThanOrEqualTo(String value) {
            addCriterion("D_CDATE <=", value, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateLike(String value) {
            addCriterion("D_CDATE like", value, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateNotLike(String value) {
            addCriterion("D_CDATE not like", value, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateIn(List<String> values) {
            addCriterion("D_CDATE in", values, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateNotIn(List<String> values) {
            addCriterion("D_CDATE not in", values, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateBetween(String value1, String value2) {
            addCriterion("D_CDATE between", value1, value2, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDCdateNotBetween(String value1, String value2) {
            addCriterion("D_CDATE not between", value1, value2, "dCdate");
            return (Criteria) this;
        }

        public Criteria andDDateIsNull() {
            addCriterion("D_DATE is null");
            return (Criteria) this;
        }

        public Criteria andDDateIsNotNull() {
            addCriterion("D_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andDDateEqualTo(String value) {
            addCriterion("D_DATE =", value, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateNotEqualTo(String value) {
            addCriterion("D_DATE <>", value, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateGreaterThan(String value) {
            addCriterion("D_DATE >", value, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateGreaterThanOrEqualTo(String value) {
            addCriterion("D_DATE >=", value, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateLessThan(String value) {
            addCriterion("D_DATE <", value, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateLessThanOrEqualTo(String value) {
            addCriterion("D_DATE <=", value, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateLike(String value) {
            addCriterion("D_DATE like", value, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateNotLike(String value) {
            addCriterion("D_DATE not like", value, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateIn(List<String> values) {
            addCriterion("D_DATE in", values, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateNotIn(List<String> values) {
            addCriterion("D_DATE not in", values, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateBetween(String value1, String value2) {
            addCriterion("D_DATE between", value1, value2, "dDate");
            return (Criteria) this;
        }

        public Criteria andDDateNotBetween(String value1, String value2) {
            addCriterion("D_DATE not between", value1, value2, "dDate");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceIsNull() {
            addCriterion("F_CONFIRMBALANCE is null");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceIsNotNull() {
            addCriterion("F_CONFIRMBALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceEqualTo(BigDecimal value) {
            addCriterion("F_CONFIRMBALANCE =", value, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceNotEqualTo(BigDecimal value) {
            addCriterion("F_CONFIRMBALANCE <>", value, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceGreaterThan(BigDecimal value) {
            addCriterion("F_CONFIRMBALANCE >", value, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_CONFIRMBALANCE >=", value, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceLessThan(BigDecimal value) {
            addCriterion("F_CONFIRMBALANCE <", value, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_CONFIRMBALANCE <=", value, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceIn(List<BigDecimal> values) {
            addCriterion("F_CONFIRMBALANCE in", values, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceNotIn(List<BigDecimal> values) {
            addCriterion("F_CONFIRMBALANCE not in", values, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_CONFIRMBALANCE between", value1, value2, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmbalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_CONFIRMBALANCE not between", value1, value2, "fConfirmbalance");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesIsNull() {
            addCriterion("F_CONFIRMSHARES is null");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesIsNotNull() {
            addCriterion("F_CONFIRMSHARES is not null");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesEqualTo(BigDecimal value) {
            addCriterion("F_CONFIRMSHARES =", value, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesNotEqualTo(BigDecimal value) {
            addCriterion("F_CONFIRMSHARES <>", value, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesGreaterThan(BigDecimal value) {
            addCriterion("F_CONFIRMSHARES >", value, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_CONFIRMSHARES >=", value, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesLessThan(BigDecimal value) {
            addCriterion("F_CONFIRMSHARES <", value, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_CONFIRMSHARES <=", value, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesIn(List<BigDecimal> values) {
            addCriterion("F_CONFIRMSHARES in", values, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesNotIn(List<BigDecimal> values) {
            addCriterion("F_CONFIRMSHARES not in", values, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_CONFIRMSHARES between", value1, value2, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andFConfirmsharesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_CONFIRMSHARES not between", value1, value2, "fConfirmshares");
            return (Criteria) this;
        }

        public Criteria andCardDateIsNull() {
            addCriterion("CARD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCardDateIsNotNull() {
            addCriterion("CARD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCardDateEqualTo(String value) {
            addCriterion("CARD_DATE =", value, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateNotEqualTo(String value) {
            addCriterion("CARD_DATE <>", value, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateGreaterThan(String value) {
            addCriterion("CARD_DATE >", value, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_DATE >=", value, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateLessThan(String value) {
            addCriterion("CARD_DATE <", value, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateLessThanOrEqualTo(String value) {
            addCriterion("CARD_DATE <=", value, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateLike(String value) {
            addCriterion("CARD_DATE like", value, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateNotLike(String value) {
            addCriterion("CARD_DATE not like", value, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateIn(List<String> values) {
            addCriterion("CARD_DATE in", values, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateNotIn(List<String> values) {
            addCriterion("CARD_DATE not in", values, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateBetween(String value1, String value2) {
            addCriterion("CARD_DATE between", value1, value2, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCardDateNotBetween(String value1, String value2) {
            addCriterion("CARD_DATE not between", value1, value2, "cardDate");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtIsNull() {
            addCriterion("CUST_OPEN_DT is null");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtIsNotNull() {
            addCriterion("CUST_OPEN_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtEqualTo(String value) {
            addCriterion("CUST_OPEN_DT =", value, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtNotEqualTo(String value) {
            addCriterion("CUST_OPEN_DT <>", value, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtGreaterThan(String value) {
            addCriterion("CUST_OPEN_DT >", value, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_OPEN_DT >=", value, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtLessThan(String value) {
            addCriterion("CUST_OPEN_DT <", value, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtLessThanOrEqualTo(String value) {
            addCriterion("CUST_OPEN_DT <=", value, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtLike(String value) {
            addCriterion("CUST_OPEN_DT like", value, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtNotLike(String value) {
            addCriterion("CUST_OPEN_DT not like", value, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtIn(List<String> values) {
            addCriterion("CUST_OPEN_DT in", values, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtNotIn(List<String> values) {
            addCriterion("CUST_OPEN_DT not in", values, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtBetween(String value1, String value2) {
            addCriterion("CUST_OPEN_DT between", value1, value2, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenDtNotBetween(String value1, String value2) {
            addCriterion("CUST_OPEN_DT not between", value1, value2, "custOpenDt");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeIsNull() {
            addCriterion("CUST_OPEN_NODE is null");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeIsNotNull() {
            addCriterion("CUST_OPEN_NODE is not null");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeEqualTo(String value) {
            addCriterion("CUST_OPEN_NODE =", value, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeNotEqualTo(String value) {
            addCriterion("CUST_OPEN_NODE <>", value, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeGreaterThan(String value) {
            addCriterion("CUST_OPEN_NODE >", value, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_OPEN_NODE >=", value, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeLessThan(String value) {
            addCriterion("CUST_OPEN_NODE <", value, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeLessThanOrEqualTo(String value) {
            addCriterion("CUST_OPEN_NODE <=", value, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeLike(String value) {
            addCriterion("CUST_OPEN_NODE like", value, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeNotLike(String value) {
            addCriterion("CUST_OPEN_NODE not like", value, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeIn(List<String> values) {
            addCriterion("CUST_OPEN_NODE in", values, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeNotIn(List<String> values) {
            addCriterion("CUST_OPEN_NODE not in", values, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeBetween(String value1, String value2) {
            addCriterion("CUST_OPEN_NODE between", value1, value2, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andCustOpenNodeNotBetween(String value1, String value2) {
            addCriterion("CUST_OPEN_NODE not between", value1, value2, "custOpenNode");
            return (Criteria) this;
        }

        public Criteria andTsbnIsNull() {
            addCriterion("TSBN is null");
            return (Criteria) this;
        }

        public Criteria andTsbnIsNotNull() {
            addCriterion("TSBN is not null");
            return (Criteria) this;
        }

        public Criteria andTsbnEqualTo(String value) {
            addCriterion("TSBN =", value, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnNotEqualTo(String value) {
            addCriterion("TSBN <>", value, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnGreaterThan(String value) {
            addCriterion("TSBN >", value, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnGreaterThanOrEqualTo(String value) {
            addCriterion("TSBN >=", value, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnLessThan(String value) {
            addCriterion("TSBN <", value, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnLessThanOrEqualTo(String value) {
            addCriterion("TSBN <=", value, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnLike(String value) {
            addCriterion("TSBN like", value, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnNotLike(String value) {
            addCriterion("TSBN not like", value, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnIn(List<String> values) {
            addCriterion("TSBN in", values, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnNotIn(List<String> values) {
            addCriterion("TSBN not in", values, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnBetween(String value1, String value2) {
            addCriterion("TSBN between", value1, value2, "tsbn");
            return (Criteria) this;
        }

        public Criteria andTsbnNotBetween(String value1, String value2) {
            addCriterion("TSBN not between", value1, value2, "tsbn");
            return (Criteria) this;
        }

        public Criteria andGuidIsNull() {
            addCriterion("GUID is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("GUID is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("GUID =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("GUID <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("GUID >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("GUID >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("GUID <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("GUID <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("GUID like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("GUID not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("GUID in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("GUID not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("GUID between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("GUID not between", value1, value2, "guid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 17 11:04:44 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ODSB_ST_TCONFIRM_TRAD
     *
     * @mbggenerated Sun Feb 17 11:04:44 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}