package pams.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PtoplogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public PtoplogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGuidIsNull() {
            addCriterion("GUID is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("GUID is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("GUID =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("GUID <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("GUID >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("GUID >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("GUID <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("GUID <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("GUID like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("GUID not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("GUID in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("GUID not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("GUID between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("GUID not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("MENU_ID is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("MENU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(String value) {
            addCriterion("MENU_ID =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(String value) {
            addCriterion("MENU_ID <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(String value) {
            addCriterion("MENU_ID >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_ID >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(String value) {
            addCriterion("MENU_ID <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(String value) {
            addCriterion("MENU_ID <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLike(String value) {
            addCriterion("MENU_ID like", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotLike(String value) {
            addCriterion("MENU_ID not like", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<String> values) {
            addCriterion("MENU_ID in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<String> values) {
            addCriterion("MENU_ID not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(String value1, String value2) {
            addCriterion("MENU_ID between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(String value1, String value2) {
            addCriterion("MENU_ID not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("MENU_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("MENU_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("MENU_NAME =", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("MENU_NAME <>", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("MENU_NAME >", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_NAME >=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("MENU_NAME <", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("MENU_NAME <=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("MENU_NAME like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("MENU_NAME not like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameIn(List<String> values) {
            addCriterion("MENU_NAME in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotIn(List<String> values) {
            addCriterion("MENU_NAME not in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("MENU_NAME between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("MENU_NAME not between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andActionIdIsNull() {
            addCriterion("ACTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andActionIdIsNotNull() {
            addCriterion("ACTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andActionIdEqualTo(String value) {
            addCriterion("ACTION_ID =", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotEqualTo(String value) {
            addCriterion("ACTION_ID <>", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdGreaterThan(String value) {
            addCriterion("ACTION_ID >", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdGreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_ID >=", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdLessThan(String value) {
            addCriterion("ACTION_ID <", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdLessThanOrEqualTo(String value) {
            addCriterion("ACTION_ID <=", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdLike(String value) {
            addCriterion("ACTION_ID like", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotLike(String value) {
            addCriterion("ACTION_ID not like", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdIn(List<String> values) {
            addCriterion("ACTION_ID in", values, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotIn(List<String> values) {
            addCriterion("ACTION_ID not in", values, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdBetween(String value1, String value2) {
            addCriterion("ACTION_ID between", value1, value2, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotBetween(String value1, String value2) {
            addCriterion("ACTION_ID not between", value1, value2, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionNameIsNull() {
            addCriterion("ACTION_NAME is null");
            return (Criteria) this;
        }

        public Criteria andActionNameIsNotNull() {
            addCriterion("ACTION_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andActionNameEqualTo(String value) {
            addCriterion("ACTION_NAME =", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameNotEqualTo(String value) {
            addCriterion("ACTION_NAME <>", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameGreaterThan(String value) {
            addCriterion("ACTION_NAME >", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_NAME >=", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameLessThan(String value) {
            addCriterion("ACTION_NAME <", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameLessThanOrEqualTo(String value) {
            addCriterion("ACTION_NAME <=", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameLike(String value) {
            addCriterion("ACTION_NAME like", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameNotLike(String value) {
            addCriterion("ACTION_NAME not like", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameIn(List<String> values) {
            addCriterion("ACTION_NAME in", values, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameNotIn(List<String> values) {
            addCriterion("ACTION_NAME not in", values, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameBetween(String value1, String value2) {
            addCriterion("ACTION_NAME between", value1, value2, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameNotBetween(String value1, String value2) {
            addCriterion("ACTION_NAME not between", value1, value2, "actionName");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("OPER_ID =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("OPER_ID <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("OPER_ID >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_ID >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("OPER_ID <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("OPER_ID <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("OPER_ID like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("OPER_ID not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("OPER_ID in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("OPER_ID not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("OPER_ID between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("OPER_ID not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperNameIsNull() {
            addCriterion("OPER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOperNameIsNotNull() {
            addCriterion("OPER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOperNameEqualTo(String value) {
            addCriterion("OPER_NAME =", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameNotEqualTo(String value) {
            addCriterion("OPER_NAME <>", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameGreaterThan(String value) {
            addCriterion("OPER_NAME >", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_NAME >=", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameLessThan(String value) {
            addCriterion("OPER_NAME <", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameLessThanOrEqualTo(String value) {
            addCriterion("OPER_NAME <=", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameLike(String value) {
            addCriterion("OPER_NAME like", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameNotLike(String value) {
            addCriterion("OPER_NAME not like", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameIn(List<String> values) {
            addCriterion("OPER_NAME in", values, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameNotIn(List<String> values) {
            addCriterion("OPER_NAME not in", values, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameBetween(String value1, String value2) {
            addCriterion("OPER_NAME between", value1, value2, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameNotBetween(String value1, String value2) {
            addCriterion("OPER_NAME not between", value1, value2, "operName");
            return (Criteria) this;
        }

        public Criteria andOperBranchidIsNull() {
            addCriterion("OPER_BRANCHID is null");
            return (Criteria) this;
        }

        public Criteria andOperBranchidIsNotNull() {
            addCriterion("OPER_BRANCHID is not null");
            return (Criteria) this;
        }

        public Criteria andOperBranchidEqualTo(String value) {
            addCriterion("OPER_BRANCHID =", value, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidNotEqualTo(String value) {
            addCriterion("OPER_BRANCHID <>", value, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidGreaterThan(String value) {
            addCriterion("OPER_BRANCHID >", value, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_BRANCHID >=", value, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidLessThan(String value) {
            addCriterion("OPER_BRANCHID <", value, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidLessThanOrEqualTo(String value) {
            addCriterion("OPER_BRANCHID <=", value, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidLike(String value) {
            addCriterion("OPER_BRANCHID like", value, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidNotLike(String value) {
            addCriterion("OPER_BRANCHID not like", value, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidIn(List<String> values) {
            addCriterion("OPER_BRANCHID in", values, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidNotIn(List<String> values) {
            addCriterion("OPER_BRANCHID not in", values, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidBetween(String value1, String value2) {
            addCriterion("OPER_BRANCHID between", value1, value2, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchidNotBetween(String value1, String value2) {
            addCriterion("OPER_BRANCHID not between", value1, value2, "operBranchid");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameIsNull() {
            addCriterion("OPER_BRANCHNAME is null");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameIsNotNull() {
            addCriterion("OPER_BRANCHNAME is not null");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameEqualTo(String value) {
            addCriterion("OPER_BRANCHNAME =", value, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameNotEqualTo(String value) {
            addCriterion("OPER_BRANCHNAME <>", value, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameGreaterThan(String value) {
            addCriterion("OPER_BRANCHNAME >", value, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_BRANCHNAME >=", value, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameLessThan(String value) {
            addCriterion("OPER_BRANCHNAME <", value, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameLessThanOrEqualTo(String value) {
            addCriterion("OPER_BRANCHNAME <=", value, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameLike(String value) {
            addCriterion("OPER_BRANCHNAME like", value, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameNotLike(String value) {
            addCriterion("OPER_BRANCHNAME not like", value, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameIn(List<String> values) {
            addCriterion("OPER_BRANCHNAME in", values, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameNotIn(List<String> values) {
            addCriterion("OPER_BRANCHNAME not in", values, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameBetween(String value1, String value2) {
            addCriterion("OPER_BRANCHNAME between", value1, value2, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOperBranchnameNotBetween(String value1, String value2) {
            addCriterion("OPER_BRANCHNAME not between", value1, value2, "operBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDateIsNull() {
            addCriterion("OP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOpDateIsNotNull() {
            addCriterion("OP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOpDateEqualTo(Date value) {
            addCriterion("OP_DATE =", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateNotEqualTo(Date value) {
            addCriterion("OP_DATE <>", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateGreaterThan(Date value) {
            addCriterion("OP_DATE >", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("OP_DATE >=", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateLessThan(Date value) {
            addCriterion("OP_DATE <", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateLessThanOrEqualTo(Date value) {
            addCriterion("OP_DATE <=", value, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateIn(List<Date> values) {
            addCriterion("OP_DATE in", values, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateNotIn(List<Date> values) {
            addCriterion("OP_DATE not in", values, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateBetween(Date value1, Date value2) {
            addCriterion("OP_DATE between", value1, value2, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDateNotBetween(Date value1, Date value2) {
            addCriterion("OP_DATE not between", value1, value2, "opDate");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidIsNull() {
            addCriterion("OP_DATA_BRANCHID is null");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidIsNotNull() {
            addCriterion("OP_DATA_BRANCHID is not null");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidEqualTo(String value) {
            addCriterion("OP_DATA_BRANCHID =", value, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidNotEqualTo(String value) {
            addCriterion("OP_DATA_BRANCHID <>", value, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidGreaterThan(String value) {
            addCriterion("OP_DATA_BRANCHID >", value, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidGreaterThanOrEqualTo(String value) {
            addCriterion("OP_DATA_BRANCHID >=", value, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidLessThan(String value) {
            addCriterion("OP_DATA_BRANCHID <", value, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidLessThanOrEqualTo(String value) {
            addCriterion("OP_DATA_BRANCHID <=", value, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidLike(String value) {
            addCriterion("OP_DATA_BRANCHID like", value, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidNotLike(String value) {
            addCriterion("OP_DATA_BRANCHID not like", value, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidIn(List<String> values) {
            addCriterion("OP_DATA_BRANCHID in", values, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidNotIn(List<String> values) {
            addCriterion("OP_DATA_BRANCHID not in", values, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidBetween(String value1, String value2) {
            addCriterion("OP_DATA_BRANCHID between", value1, value2, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchidNotBetween(String value1, String value2) {
            addCriterion("OP_DATA_BRANCHID not between", value1, value2, "opDataBranchid");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameIsNull() {
            addCriterion("OP_DATA_BRANCHNAME is null");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameIsNotNull() {
            addCriterion("OP_DATA_BRANCHNAME is not null");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameEqualTo(String value) {
            addCriterion("OP_DATA_BRANCHNAME =", value, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameNotEqualTo(String value) {
            addCriterion("OP_DATA_BRANCHNAME <>", value, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameGreaterThan(String value) {
            addCriterion("OP_DATA_BRANCHNAME >", value, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameGreaterThanOrEqualTo(String value) {
            addCriterion("OP_DATA_BRANCHNAME >=", value, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameLessThan(String value) {
            addCriterion("OP_DATA_BRANCHNAME <", value, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameLessThanOrEqualTo(String value) {
            addCriterion("OP_DATA_BRANCHNAME <=", value, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameLike(String value) {
            addCriterion("OP_DATA_BRANCHNAME like", value, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameNotLike(String value) {
            addCriterion("OP_DATA_BRANCHNAME not like", value, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameIn(List<String> values) {
            addCriterion("OP_DATA_BRANCHNAME in", values, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameNotIn(List<String> values) {
            addCriterion("OP_DATA_BRANCHNAME not in", values, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameBetween(String value1, String value2) {
            addCriterion("OP_DATA_BRANCHNAME between", value1, value2, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataBranchnameNotBetween(String value1, String value2) {
            addCriterion("OP_DATA_BRANCHNAME not between", value1, value2, "opDataBranchname");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateIsNull() {
            addCriterion("OP_DATA_STARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateIsNotNull() {
            addCriterion("OP_DATA_STARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateEqualTo(String value) {
            addCriterion("OP_DATA_STARTDATE =", value, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateNotEqualTo(String value) {
            addCriterion("OP_DATA_STARTDATE <>", value, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateGreaterThan(String value) {
            addCriterion("OP_DATA_STARTDATE >", value, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("OP_DATA_STARTDATE >=", value, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateLessThan(String value) {
            addCriterion("OP_DATA_STARTDATE <", value, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateLessThanOrEqualTo(String value) {
            addCriterion("OP_DATA_STARTDATE <=", value, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateLike(String value) {
            addCriterion("OP_DATA_STARTDATE like", value, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateNotLike(String value) {
            addCriterion("OP_DATA_STARTDATE not like", value, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateIn(List<String> values) {
            addCriterion("OP_DATA_STARTDATE in", values, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateNotIn(List<String> values) {
            addCriterion("OP_DATA_STARTDATE not in", values, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateBetween(String value1, String value2) {
            addCriterion("OP_DATA_STARTDATE between", value1, value2, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataStartdateNotBetween(String value1, String value2) {
            addCriterion("OP_DATA_STARTDATE not between", value1, value2, "opDataStartdate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateIsNull() {
            addCriterion("OP_DATA_ENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateIsNotNull() {
            addCriterion("OP_DATA_ENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateEqualTo(String value) {
            addCriterion("OP_DATA_ENDDATE =", value, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateNotEqualTo(String value) {
            addCriterion("OP_DATA_ENDDATE <>", value, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateGreaterThan(String value) {
            addCriterion("OP_DATA_ENDDATE >", value, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateGreaterThanOrEqualTo(String value) {
            addCriterion("OP_DATA_ENDDATE >=", value, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateLessThan(String value) {
            addCriterion("OP_DATA_ENDDATE <", value, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateLessThanOrEqualTo(String value) {
            addCriterion("OP_DATA_ENDDATE <=", value, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateLike(String value) {
            addCriterion("OP_DATA_ENDDATE like", value, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateNotLike(String value) {
            addCriterion("OP_DATA_ENDDATE not like", value, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateIn(List<String> values) {
            addCriterion("OP_DATA_ENDDATE in", values, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateNotIn(List<String> values) {
            addCriterion("OP_DATA_ENDDATE not in", values, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateBetween(String value1, String value2) {
            addCriterion("OP_DATA_ENDDATE between", value1, value2, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpDataEnddateNotBetween(String value1, String value2) {
            addCriterion("OP_DATA_ENDDATE not between", value1, value2, "opDataEnddate");
            return (Criteria) this;
        }

        public Criteria andOpLogIsNull() {
            addCriterion("OP_LOG is null");
            return (Criteria) this;
        }

        public Criteria andOpLogIsNotNull() {
            addCriterion("OP_LOG is not null");
            return (Criteria) this;
        }

        public Criteria andOpLogEqualTo(String value) {
            addCriterion("OP_LOG =", value, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogNotEqualTo(String value) {
            addCriterion("OP_LOG <>", value, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogGreaterThan(String value) {
            addCriterion("OP_LOG >", value, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogGreaterThanOrEqualTo(String value) {
            addCriterion("OP_LOG >=", value, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogLessThan(String value) {
            addCriterion("OP_LOG <", value, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogLessThanOrEqualTo(String value) {
            addCriterion("OP_LOG <=", value, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogLike(String value) {
            addCriterion("OP_LOG like", value, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogNotLike(String value) {
            addCriterion("OP_LOG not like", value, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogIn(List<String> values) {
            addCriterion("OP_LOG in", values, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogNotIn(List<String> values) {
            addCriterion("OP_LOG not in", values, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogBetween(String value1, String value2) {
            addCriterion("OP_LOG between", value1, value2, "opLog");
            return (Criteria) this;
        }

        public Criteria andOpLogNotBetween(String value1, String value2) {
            addCriterion("OP_LOG not between", value1, value2, "opLog");
            return (Criteria) this;
        }

        public Criteria andHostIpIsNull() {
            addCriterion("HOST_IP is null");
            return (Criteria) this;
        }

        public Criteria andHostIpIsNotNull() {
            addCriterion("HOST_IP is not null");
            return (Criteria) this;
        }

        public Criteria andHostIpEqualTo(String value) {
            addCriterion("HOST_IP =", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotEqualTo(String value) {
            addCriterion("HOST_IP <>", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpGreaterThan(String value) {
            addCriterion("HOST_IP >", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpGreaterThanOrEqualTo(String value) {
            addCriterion("HOST_IP >=", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpLessThan(String value) {
            addCriterion("HOST_IP <", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpLessThanOrEqualTo(String value) {
            addCriterion("HOST_IP <=", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpLike(String value) {
            addCriterion("HOST_IP like", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotLike(String value) {
            addCriterion("HOST_IP not like", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpIn(List<String> values) {
            addCriterion("HOST_IP in", values, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotIn(List<String> values) {
            addCriterion("HOST_IP not in", values, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpBetween(String value1, String value2) {
            addCriterion("HOST_IP between", value1, value2, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotBetween(String value1, String value2) {
            addCriterion("HOST_IP not between", value1, value2, "hostIp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTOPLOG
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 06 09:39:50 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PTOPLOG
     *
     * @mbggenerated Sun Jan 06 09:39:50 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}