package pams.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SvClsCustinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public SvClsCustinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGuidIsNull() {
            addCriterion("GUID is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("GUID is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("GUID =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("GUID <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("GUID >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("GUID >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("GUID <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("GUID <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("GUID like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("GUID not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("GUID in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("GUID not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("GUID between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("GUID not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andBranchNameIsNull() {
            addCriterion("BRANCH_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBranchNameIsNotNull() {
            addCriterion("BRANCH_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBranchNameEqualTo(String value) {
            addCriterion("BRANCH_NAME =", value, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameNotEqualTo(String value) {
            addCriterion("BRANCH_NAME <>", value, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameGreaterThan(String value) {
            addCriterion("BRANCH_NAME >", value, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH_NAME >=", value, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameLessThan(String value) {
            addCriterion("BRANCH_NAME <", value, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameLessThanOrEqualTo(String value) {
            addCriterion("BRANCH_NAME <=", value, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameLike(String value) {
            addCriterion("BRANCH_NAME like", value, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameNotLike(String value) {
            addCriterion("BRANCH_NAME not like", value, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameIn(List<String> values) {
            addCriterion("BRANCH_NAME in", values, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameNotIn(List<String> values) {
            addCriterion("BRANCH_NAME not in", values, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameBetween(String value1, String value2) {
            addCriterion("BRANCH_NAME between", value1, value2, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchNameNotBetween(String value1, String value2) {
            addCriterion("BRANCH_NAME not between", value1, value2, "branchName");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNull() {
            addCriterion("BRANCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNotNull() {
            addCriterion("BRANCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBranchIdEqualTo(String value) {
            addCriterion("BRANCH_ID =", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotEqualTo(String value) {
            addCriterion("BRANCH_ID <>", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThan(String value) {
            addCriterion("BRANCH_ID >", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH_ID >=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThan(String value) {
            addCriterion("BRANCH_ID <", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThanOrEqualTo(String value) {
            addCriterion("BRANCH_ID <=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLike(String value) {
            addCriterion("BRANCH_ID like", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotLike(String value) {
            addCriterion("BRANCH_ID not like", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdIn(List<String> values) {
            addCriterion("BRANCH_ID in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotIn(List<String> values) {
            addCriterion("BRANCH_ID not in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdBetween(String value1, String value2) {
            addCriterion("BRANCH_ID between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotBetween(String value1, String value2) {
            addCriterion("BRANCH_ID not between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("CUST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("CUST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("CUST_NAME =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("CUST_NAME <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("CUST_NAME >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NAME >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("CUST_NAME <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("CUST_NAME <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("CUST_NAME like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("CUST_NAME not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("CUST_NAME in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("CUST_NAME not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("CUST_NAME between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("CUST_NAME not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCertTypeIsNull() {
            addCriterion("CERT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCertTypeIsNotNull() {
            addCriterion("CERT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCertTypeEqualTo(String value) {
            addCriterion("CERT_TYPE =", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotEqualTo(String value) {
            addCriterion("CERT_TYPE <>", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeGreaterThan(String value) {
            addCriterion("CERT_TYPE >", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CERT_TYPE >=", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLessThan(String value) {
            addCriterion("CERT_TYPE <", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLessThanOrEqualTo(String value) {
            addCriterion("CERT_TYPE <=", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLike(String value) {
            addCriterion("CERT_TYPE like", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotLike(String value) {
            addCriterion("CERT_TYPE not like", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeIn(List<String> values) {
            addCriterion("CERT_TYPE in", values, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotIn(List<String> values) {
            addCriterion("CERT_TYPE not in", values, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeBetween(String value1, String value2) {
            addCriterion("CERT_TYPE between", value1, value2, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotBetween(String value1, String value2) {
            addCriterion("CERT_TYPE not between", value1, value2, "certType");
            return (Criteria) this;
        }

        public Criteria andCertNoIsNull() {
            addCriterion("CERT_NO is null");
            return (Criteria) this;
        }

        public Criteria andCertNoIsNotNull() {
            addCriterion("CERT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCertNoEqualTo(String value) {
            addCriterion("CERT_NO =", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotEqualTo(String value) {
            addCriterion("CERT_NO <>", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoGreaterThan(String value) {
            addCriterion("CERT_NO >", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoGreaterThanOrEqualTo(String value) {
            addCriterion("CERT_NO >=", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLessThan(String value) {
            addCriterion("CERT_NO <", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLessThanOrEqualTo(String value) {
            addCriterion("CERT_NO <=", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLike(String value) {
            addCriterion("CERT_NO like", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotLike(String value) {
            addCriterion("CERT_NO not like", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoIn(List<String> values) {
            addCriterion("CERT_NO in", values, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotIn(List<String> values) {
            addCriterion("CERT_NO not in", values, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoBetween(String value1, String value2) {
            addCriterion("CERT_NO between", value1, value2, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotBetween(String value1, String value2) {
            addCriterion("CERT_NO not between", value1, value2, "certNo");
            return (Criteria) this;
        }

        public Criteria andContactInfo1IsNull() {
            addCriterion("CONTACT_INFO1 is null");
            return (Criteria) this;
        }

        public Criteria andContactInfo1IsNotNull() {
            addCriterion("CONTACT_INFO1 is not null");
            return (Criteria) this;
        }

        public Criteria andContactInfo1EqualTo(String value) {
            addCriterion("CONTACT_INFO1 =", value, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1NotEqualTo(String value) {
            addCriterion("CONTACT_INFO1 <>", value, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1GreaterThan(String value) {
            addCriterion("CONTACT_INFO1 >", value, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1GreaterThanOrEqualTo(String value) {
            addCriterion("CONTACT_INFO1 >=", value, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1LessThan(String value) {
            addCriterion("CONTACT_INFO1 <", value, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1LessThanOrEqualTo(String value) {
            addCriterion("CONTACT_INFO1 <=", value, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1Like(String value) {
            addCriterion("CONTACT_INFO1 like", value, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1NotLike(String value) {
            addCriterion("CONTACT_INFO1 not like", value, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1In(List<String> values) {
            addCriterion("CONTACT_INFO1 in", values, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1NotIn(List<String> values) {
            addCriterion("CONTACT_INFO1 not in", values, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1Between(String value1, String value2) {
            addCriterion("CONTACT_INFO1 between", value1, value2, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo1NotBetween(String value1, String value2) {
            addCriterion("CONTACT_INFO1 not between", value1, value2, "contactInfo1");
            return (Criteria) this;
        }

        public Criteria andContactInfo2IsNull() {
            addCriterion("CONTACT_INFO2 is null");
            return (Criteria) this;
        }

        public Criteria andContactInfo2IsNotNull() {
            addCriterion("CONTACT_INFO2 is not null");
            return (Criteria) this;
        }

        public Criteria andContactInfo2EqualTo(String value) {
            addCriterion("CONTACT_INFO2 =", value, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2NotEqualTo(String value) {
            addCriterion("CONTACT_INFO2 <>", value, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2GreaterThan(String value) {
            addCriterion("CONTACT_INFO2 >", value, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2GreaterThanOrEqualTo(String value) {
            addCriterion("CONTACT_INFO2 >=", value, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2LessThan(String value) {
            addCriterion("CONTACT_INFO2 <", value, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2LessThanOrEqualTo(String value) {
            addCriterion("CONTACT_INFO2 <=", value, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2Like(String value) {
            addCriterion("CONTACT_INFO2 like", value, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2NotLike(String value) {
            addCriterion("CONTACT_INFO2 not like", value, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2In(List<String> values) {
            addCriterion("CONTACT_INFO2 in", values, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2NotIn(List<String> values) {
            addCriterion("CONTACT_INFO2 not in", values, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2Between(String value1, String value2) {
            addCriterion("CONTACT_INFO2 between", value1, value2, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andContactInfo2NotBetween(String value1, String value2) {
            addCriterion("CONTACT_INFO2 not between", value1, value2, "contactInfo2");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrIsNull() {
            addCriterion("AUM_MONTH_CURR is null");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrIsNotNull() {
            addCriterion("AUM_MONTH_CURR is not null");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrEqualTo(BigDecimal value) {
            addCriterion("AUM_MONTH_CURR =", value, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrNotEqualTo(BigDecimal value) {
            addCriterion("AUM_MONTH_CURR <>", value, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrGreaterThan(BigDecimal value) {
            addCriterion("AUM_MONTH_CURR >", value, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AUM_MONTH_CURR >=", value, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrLessThan(BigDecimal value) {
            addCriterion("AUM_MONTH_CURR <", value, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AUM_MONTH_CURR <=", value, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrIn(List<BigDecimal> values) {
            addCriterion("AUM_MONTH_CURR in", values, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrNotIn(List<BigDecimal> values) {
            addCriterion("AUM_MONTH_CURR not in", values, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUM_MONTH_CURR between", value1, value2, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthCurrNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUM_MONTH_CURR not between", value1, value2, "aumMonthCurr");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastIsNull() {
            addCriterion("AUM_MONTH_LAST is null");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastIsNotNull() {
            addCriterion("AUM_MONTH_LAST is not null");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastEqualTo(BigDecimal value) {
            addCriterion("AUM_MONTH_LAST =", value, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastNotEqualTo(BigDecimal value) {
            addCriterion("AUM_MONTH_LAST <>", value, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastGreaterThan(BigDecimal value) {
            addCriterion("AUM_MONTH_LAST >", value, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AUM_MONTH_LAST >=", value, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastLessThan(BigDecimal value) {
            addCriterion("AUM_MONTH_LAST <", value, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AUM_MONTH_LAST <=", value, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastIn(List<BigDecimal> values) {
            addCriterion("AUM_MONTH_LAST in", values, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastNotIn(List<BigDecimal> values) {
            addCriterion("AUM_MONTH_LAST not in", values, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUM_MONTH_LAST between", value1, value2, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumMonthLastNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUM_MONTH_LAST not between", value1, value2, "aumMonthLast");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepIsNull() {
            addCriterion("AUM_TIMEPOINT_DEP is null");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepIsNotNull() {
            addCriterion("AUM_TIMEPOINT_DEP is not null");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepEqualTo(BigDecimal value) {
            addCriterion("AUM_TIMEPOINT_DEP =", value, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepNotEqualTo(BigDecimal value) {
            addCriterion("AUM_TIMEPOINT_DEP <>", value, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepGreaterThan(BigDecimal value) {
            addCriterion("AUM_TIMEPOINT_DEP >", value, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AUM_TIMEPOINT_DEP >=", value, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepLessThan(BigDecimal value) {
            addCriterion("AUM_TIMEPOINT_DEP <", value, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AUM_TIMEPOINT_DEP <=", value, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepIn(List<BigDecimal> values) {
            addCriterion("AUM_TIMEPOINT_DEP in", values, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepNotIn(List<BigDecimal> values) {
            addCriterion("AUM_TIMEPOINT_DEP not in", values, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUM_TIMEPOINT_DEP between", value1, value2, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andAumTimepointDepNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUM_TIMEPOINT_DEP not between", value1, value2, "aumTimepointDep");
            return (Criteria) this;
        }

        public Criteria andLoanBalIsNull() {
            addCriterion("LOAN_BAL is null");
            return (Criteria) this;
        }

        public Criteria andLoanBalIsNotNull() {
            addCriterion("LOAN_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andLoanBalEqualTo(BigDecimal value) {
            addCriterion("LOAN_BAL =", value, "loanBal");
            return (Criteria) this;
        }

        public Criteria andLoanBalNotEqualTo(BigDecimal value) {
            addCriterion("LOAN_BAL <>", value, "loanBal");
            return (Criteria) this;
        }

        public Criteria andLoanBalGreaterThan(BigDecimal value) {
            addCriterion("LOAN_BAL >", value, "loanBal");
            return (Criteria) this;
        }

        public Criteria andLoanBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOAN_BAL >=", value, "loanBal");
            return (Criteria) this;
        }

        public Criteria andLoanBalLessThan(BigDecimal value) {
            addCriterion("LOAN_BAL <", value, "loanBal");
            return (Criteria) this;
        }

        public Criteria andLoanBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOAN_BAL <=", value, "loanBal");
            return (Criteria) this;
        }

        public Criteria andLoanBalIn(List<BigDecimal> values) {
            addCriterion("LOAN_BAL in", values, "loanBal");
            return (Criteria) this;
        }

        public Criteria andLoanBalNotIn(List<BigDecimal> values) {
            addCriterion("LOAN_BAL not in", values, "loanBal");
            return (Criteria) this;
        }

        public Criteria andLoanBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOAN_BAL between", value1, value2, "loanBal");
            return (Criteria) this;
        }

        public Criteria andLoanBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOAN_BAL not between", value1, value2, "loanBal");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdIsNull() {
            addCriterion("OPENACT_BRANCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdIsNotNull() {
            addCriterion("OPENACT_BRANCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdEqualTo(String value) {
            addCriterion("OPENACT_BRANCH_ID =", value, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdNotEqualTo(String value) {
            addCriterion("OPENACT_BRANCH_ID <>", value, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdGreaterThan(String value) {
            addCriterion("OPENACT_BRANCH_ID >", value, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPENACT_BRANCH_ID >=", value, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdLessThan(String value) {
            addCriterion("OPENACT_BRANCH_ID <", value, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdLessThanOrEqualTo(String value) {
            addCriterion("OPENACT_BRANCH_ID <=", value, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdLike(String value) {
            addCriterion("OPENACT_BRANCH_ID like", value, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdNotLike(String value) {
            addCriterion("OPENACT_BRANCH_ID not like", value, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdIn(List<String> values) {
            addCriterion("OPENACT_BRANCH_ID in", values, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdNotIn(List<String> values) {
            addCriterion("OPENACT_BRANCH_ID not in", values, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdBetween(String value1, String value2) {
            addCriterion("OPENACT_BRANCH_ID between", value1, value2, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchIdNotBetween(String value1, String value2) {
            addCriterion("OPENACT_BRANCH_ID not between", value1, value2, "openactBranchId");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameIsNull() {
            addCriterion("OPENACT_BRANCH_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameIsNotNull() {
            addCriterion("OPENACT_BRANCH_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameEqualTo(String value) {
            addCriterion("OPENACT_BRANCH_NAME =", value, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameNotEqualTo(String value) {
            addCriterion("OPENACT_BRANCH_NAME <>", value, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameGreaterThan(String value) {
            addCriterion("OPENACT_BRANCH_NAME >", value, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameGreaterThanOrEqualTo(String value) {
            addCriterion("OPENACT_BRANCH_NAME >=", value, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameLessThan(String value) {
            addCriterion("OPENACT_BRANCH_NAME <", value, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameLessThanOrEqualTo(String value) {
            addCriterion("OPENACT_BRANCH_NAME <=", value, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameLike(String value) {
            addCriterion("OPENACT_BRANCH_NAME like", value, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameNotLike(String value) {
            addCriterion("OPENACT_BRANCH_NAME not like", value, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameIn(List<String> values) {
            addCriterion("OPENACT_BRANCH_NAME in", values, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameNotIn(List<String> values) {
            addCriterion("OPENACT_BRANCH_NAME not in", values, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameBetween(String value1, String value2) {
            addCriterion("OPENACT_BRANCH_NAME between", value1, value2, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andOpenactBranchNameNotBetween(String value1, String value2) {
            addCriterion("OPENACT_BRANCH_NAME not between", value1, value2, "openactBranchName");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalIsNull() {
            addCriterion("CTS_MARGIN_BAL is null");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalIsNotNull() {
            addCriterion("CTS_MARGIN_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalEqualTo(BigDecimal value) {
            addCriterion("CTS_MARGIN_BAL =", value, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalNotEqualTo(BigDecimal value) {
            addCriterion("CTS_MARGIN_BAL <>", value, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalGreaterThan(BigDecimal value) {
            addCriterion("CTS_MARGIN_BAL >", value, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CTS_MARGIN_BAL >=", value, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalLessThan(BigDecimal value) {
            addCriterion("CTS_MARGIN_BAL <", value, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CTS_MARGIN_BAL <=", value, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalIn(List<BigDecimal> values) {
            addCriterion("CTS_MARGIN_BAL in", values, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalNotIn(List<BigDecimal> values) {
            addCriterion("CTS_MARGIN_BAL not in", values, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CTS_MARGIN_BAL between", value1, value2, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andCtsMarginBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CTS_MARGIN_BAL not between", value1, value2, "ctsMarginBal");
            return (Criteria) this;
        }

        public Criteria andRptDateIsNull() {
            addCriterion("RPT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRptDateIsNotNull() {
            addCriterion("RPT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRptDateEqualTo(String value) {
            addCriterion("RPT_DATE =", value, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateNotEqualTo(String value) {
            addCriterion("RPT_DATE <>", value, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateGreaterThan(String value) {
            addCriterion("RPT_DATE >", value, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateGreaterThanOrEqualTo(String value) {
            addCriterion("RPT_DATE >=", value, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateLessThan(String value) {
            addCriterion("RPT_DATE <", value, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateLessThanOrEqualTo(String value) {
            addCriterion("RPT_DATE <=", value, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateLike(String value) {
            addCriterion("RPT_DATE like", value, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateNotLike(String value) {
            addCriterion("RPT_DATE not like", value, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateIn(List<String> values) {
            addCriterion("RPT_DATE in", values, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateNotIn(List<String> values) {
            addCriterion("RPT_DATE not in", values, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateBetween(String value1, String value2) {
            addCriterion("RPT_DATE between", value1, value2, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptDateNotBetween(String value1, String value2) {
            addCriterion("RPT_DATE not between", value1, value2, "rptDate");
            return (Criteria) this;
        }

        public Criteria andRptTypeIsNull() {
            addCriterion("RPT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRptTypeIsNotNull() {
            addCriterion("RPT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRptTypeEqualTo(String value) {
            addCriterion("RPT_TYPE =", value, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeNotEqualTo(String value) {
            addCriterion("RPT_TYPE <>", value, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeGreaterThan(String value) {
            addCriterion("RPT_TYPE >", value, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeGreaterThanOrEqualTo(String value) {
            addCriterion("RPT_TYPE >=", value, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeLessThan(String value) {
            addCriterion("RPT_TYPE <", value, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeLessThanOrEqualTo(String value) {
            addCriterion("RPT_TYPE <=", value, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeLike(String value) {
            addCriterion("RPT_TYPE like", value, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeNotLike(String value) {
            addCriterion("RPT_TYPE not like", value, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeIn(List<String> values) {
            addCriterion("RPT_TYPE in", values, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeNotIn(List<String> values) {
            addCriterion("RPT_TYPE not in", values, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeBetween(String value1, String value2) {
            addCriterion("RPT_TYPE between", value1, value2, "rptType");
            return (Criteria) this;
        }

        public Criteria andRptTypeNotBetween(String value1, String value2) {
            addCriterion("RPT_TYPE not between", value1, value2, "rptType");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("OPER_ID =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("OPER_ID <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("OPER_ID >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_ID >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("OPER_ID <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("OPER_ID <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("OPER_ID like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("OPER_ID not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("OPER_ID in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("OPER_ID not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("OPER_ID between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("OPER_ID not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNull() {
            addCriterion("OPER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNotNull() {
            addCriterion("OPER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperDateEqualTo(Date value) {
            addCriterion("OPER_DATE =", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotEqualTo(Date value) {
            addCriterion("OPER_DATE <>", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThan(Date value) {
            addCriterion("OPER_DATE >", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPER_DATE >=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThan(Date value) {
            addCriterion("OPER_DATE <", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThanOrEqualTo(Date value) {
            addCriterion("OPER_DATE <=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIn(List<Date> values) {
            addCriterion("OPER_DATE in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotIn(List<Date> values) {
            addCriterion("OPER_DATE not in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateBetween(Date value1, Date value2) {
            addCriterion("OPER_DATE between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotBetween(Date value1, Date value2) {
            addCriterion("OPER_DATE not between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andImpDateIsNull() {
            addCriterion("IMP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andImpDateIsNotNull() {
            addCriterion("IMP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andImpDateEqualTo(Date value) {
            addCriterion("IMP_DATE =", value, "impDate");
            return (Criteria) this;
        }

        public Criteria andImpDateNotEqualTo(Date value) {
            addCriterion("IMP_DATE <>", value, "impDate");
            return (Criteria) this;
        }

        public Criteria andImpDateGreaterThan(Date value) {
            addCriterion("IMP_DATE >", value, "impDate");
            return (Criteria) this;
        }

        public Criteria andImpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("IMP_DATE >=", value, "impDate");
            return (Criteria) this;
        }

        public Criteria andImpDateLessThan(Date value) {
            addCriterion("IMP_DATE <", value, "impDate");
            return (Criteria) this;
        }

        public Criteria andImpDateLessThanOrEqualTo(Date value) {
            addCriterion("IMP_DATE <=", value, "impDate");
            return (Criteria) this;
        }

        public Criteria andImpDateIn(List<Date> values) {
            addCriterion("IMP_DATE in", values, "impDate");
            return (Criteria) this;
        }

        public Criteria andImpDateNotIn(List<Date> values) {
            addCriterion("IMP_DATE not in", values, "impDate");
            return (Criteria) this;
        }

        public Criteria andImpDateBetween(Date value1, Date value2) {
            addCriterion("IMP_DATE between", value1, value2, "impDate");
            return (Criteria) this;
        }

        public Criteria andImpDateNotBetween(Date value1, Date value2) {
            addCriterion("IMP_DATE not between", value1, value2, "impDate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(String value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(String value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(String value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(String value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLike(String value) {
            addCriterion("DELETE_FLAG like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotLike(String value) {
            addCriterion("DELETE_FLAG not like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<String> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<String> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNull() {
            addCriterion("BANK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNotNull() {
            addCriterion("BANK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBankIdEqualTo(String value) {
            addCriterion("BANK_ID =", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotEqualTo(String value) {
            addCriterion("BANK_ID <>", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThan(String value) {
            addCriterion("BANK_ID >", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_ID >=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThan(String value) {
            addCriterion("BANK_ID <", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThanOrEqualTo(String value) {
            addCriterion("BANK_ID <=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLike(String value) {
            addCriterion("BANK_ID like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotLike(String value) {
            addCriterion("BANK_ID not like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdIn(List<String> values) {
            addCriterion("BANK_ID in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotIn(List<String> values) {
            addCriterion("BANK_ID not in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdBetween(String value1, String value2) {
            addCriterion("BANK_ID between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotBetween(String value1, String value2) {
            addCriterion("BANK_ID not between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeIsNull() {
            addCriterion("CUST_NO_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeIsNotNull() {
            addCriterion("CUST_NO_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeEqualTo(String value) {
            addCriterion("CUST_NO_TYPE =", value, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeNotEqualTo(String value) {
            addCriterion("CUST_NO_TYPE <>", value, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeGreaterThan(String value) {
            addCriterion("CUST_NO_TYPE >", value, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NO_TYPE >=", value, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeLessThan(String value) {
            addCriterion("CUST_NO_TYPE <", value, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeLessThanOrEqualTo(String value) {
            addCriterion("CUST_NO_TYPE <=", value, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeLike(String value) {
            addCriterion("CUST_NO_TYPE like", value, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeNotLike(String value) {
            addCriterion("CUST_NO_TYPE not like", value, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeIn(List<String> values) {
            addCriterion("CUST_NO_TYPE in", values, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeNotIn(List<String> values) {
            addCriterion("CUST_NO_TYPE not in", values, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeBetween(String value1, String value2) {
            addCriterion("CUST_NO_TYPE between", value1, value2, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoTypeNotBetween(String value1, String value2) {
            addCriterion("CUST_NO_TYPE not between", value1, value2, "custNoType");
            return (Criteria) this;
        }

        public Criteria andCustNoIsNull() {
            addCriterion("CUST_NO is null");
            return (Criteria) this;
        }

        public Criteria andCustNoIsNotNull() {
            addCriterion("CUST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCustNoEqualTo(String value) {
            addCriterion("CUST_NO =", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotEqualTo(String value) {
            addCriterion("CUST_NO <>", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThan(String value) {
            addCriterion("CUST_NO >", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NO >=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThan(String value) {
            addCriterion("CUST_NO <", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThanOrEqualTo(String value) {
            addCriterion("CUST_NO <=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLike(String value) {
            addCriterion("CUST_NO like", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotLike(String value) {
            addCriterion("CUST_NO not like", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoIn(List<String> values) {
            addCriterion("CUST_NO in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotIn(List<String> values) {
            addCriterion("CUST_NO not in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoBetween(String value1, String value2) {
            addCriterion("CUST_NO between", value1, value2, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotBetween(String value1, String value2) {
            addCriterion("CUST_NO not between", value1, value2, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustGenderIsNull() {
            addCriterion("CUST_GENDER is null");
            return (Criteria) this;
        }

        public Criteria andCustGenderIsNotNull() {
            addCriterion("CUST_GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andCustGenderEqualTo(String value) {
            addCriterion("CUST_GENDER =", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderNotEqualTo(String value) {
            addCriterion("CUST_GENDER <>", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderGreaterThan(String value) {
            addCriterion("CUST_GENDER >", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_GENDER >=", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderLessThan(String value) {
            addCriterion("CUST_GENDER <", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderLessThanOrEqualTo(String value) {
            addCriterion("CUST_GENDER <=", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderLike(String value) {
            addCriterion("CUST_GENDER like", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderNotLike(String value) {
            addCriterion("CUST_GENDER not like", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderIn(List<String> values) {
            addCriterion("CUST_GENDER in", values, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderNotIn(List<String> values) {
            addCriterion("CUST_GENDER not in", values, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderBetween(String value1, String value2) {
            addCriterion("CUST_GENDER between", value1, value2, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderNotBetween(String value1, String value2) {
            addCriterion("CUST_GENDER not between", value1, value2, "custGender");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 16 09:52:56 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SV_CLS_CUSTINFO
     *
     * @mbggenerated Tue Jul 16 09:52:56 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}