package pams.repository.model;

import java.math.BigDecimal;

public class Svpssaleprdckpt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.GUID
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CKPTID
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private String ckptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.SALEPRDID
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private String saleprdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CHECKFLAG
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private String checkflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CHECKDATE
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private String checkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CHECKTIME
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private String checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CHECKTIMES
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private Long checktimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CHECKLOG
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private String checklog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CHPTTYPE
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private String chpttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CHPTSWITCH
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private String chptswitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CHPTAMT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private BigDecimal chptamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSSALEPRDCKPT.CHPTNUM
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    private BigDecimal chptnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.GUID
     *
     * @return the value of SVPSSALEPRDCKPT.GUID
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.GUID
     *
     * @param guid the value for SVPSSALEPRDCKPT.GUID
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CKPTID
     *
     * @return the value of SVPSSALEPRDCKPT.CKPTID
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public String getCkptid() {
        return ckptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CKPTID
     *
     * @param ckptid the value for SVPSSALEPRDCKPT.CKPTID
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setCkptid(String ckptid) {
        this.ckptid = ckptid == null ? null : ckptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.SALEPRDID
     *
     * @return the value of SVPSSALEPRDCKPT.SALEPRDID
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public String getSaleprdid() {
        return saleprdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.SALEPRDID
     *
     * @param saleprdid the value for SVPSSALEPRDCKPT.SALEPRDID
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setSaleprdid(String saleprdid) {
        this.saleprdid = saleprdid == null ? null : saleprdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CHECKFLAG
     *
     * @return the value of SVPSSALEPRDCKPT.CHECKFLAG
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public String getCheckflag() {
        return checkflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CHECKFLAG
     *
     * @param checkflag the value for SVPSSALEPRDCKPT.CHECKFLAG
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setCheckflag(String checkflag) {
        this.checkflag = checkflag == null ? null : checkflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CHECKDATE
     *
     * @return the value of SVPSSALEPRDCKPT.CHECKDATE
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public String getCheckdate() {
        return checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CHECKDATE
     *
     * @param checkdate the value for SVPSSALEPRDCKPT.CHECKDATE
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setCheckdate(String checkdate) {
        this.checkdate = checkdate == null ? null : checkdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CHECKTIME
     *
     * @return the value of SVPSSALEPRDCKPT.CHECKTIME
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public String getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CHECKTIME
     *
     * @param checktime the value for SVPSSALEPRDCKPT.CHECKTIME
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setChecktime(String checktime) {
        this.checktime = checktime == null ? null : checktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CHECKTIMES
     *
     * @return the value of SVPSSALEPRDCKPT.CHECKTIMES
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public Long getChecktimes() {
        return checktimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CHECKTIMES
     *
     * @param checktimes the value for SVPSSALEPRDCKPT.CHECKTIMES
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setChecktimes(Long checktimes) {
        this.checktimes = checktimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CHECKLOG
     *
     * @return the value of SVPSSALEPRDCKPT.CHECKLOG
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public String getChecklog() {
        return checklog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CHECKLOG
     *
     * @param checklog the value for SVPSSALEPRDCKPT.CHECKLOG
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setChecklog(String checklog) {
        this.checklog = checklog == null ? null : checklog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CHPTTYPE
     *
     * @return the value of SVPSSALEPRDCKPT.CHPTTYPE
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public String getChpttype() {
        return chpttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CHPTTYPE
     *
     * @param chpttype the value for SVPSSALEPRDCKPT.CHPTTYPE
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setChpttype(String chpttype) {
        this.chpttype = chpttype == null ? null : chpttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CHPTSWITCH
     *
     * @return the value of SVPSSALEPRDCKPT.CHPTSWITCH
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public String getChptswitch() {
        return chptswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CHPTSWITCH
     *
     * @param chptswitch the value for SVPSSALEPRDCKPT.CHPTSWITCH
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setChptswitch(String chptswitch) {
        this.chptswitch = chptswitch == null ? null : chptswitch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CHPTAMT
     *
     * @return the value of SVPSSALEPRDCKPT.CHPTAMT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public BigDecimal getChptamt() {
        return chptamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CHPTAMT
     *
     * @param chptamt the value for SVPSSALEPRDCKPT.CHPTAMT
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setChptamt(BigDecimal chptamt) {
        this.chptamt = chptamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSSALEPRDCKPT.CHPTNUM
     *
     * @return the value of SVPSSALEPRDCKPT.CHPTNUM
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public BigDecimal getChptnum() {
        return chptnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSSALEPRDCKPT.CHPTNUM
     *
     * @param chptnum the value for SVPSSALEPRDCKPT.CHPTNUM
     *
     * @mbggenerated Tue May 17 22:07:54 CST 2011
     */
    public void setChptnum(BigDecimal chptnum) {
        this.chptnum = chptnum;
    }
}