package pams.repository.model;

public class Svpsprdckptdef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSPRDCKPTDEF.GUID
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSPRDCKPTDEF.PRDID
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    private String prdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSPRDCKPTDEF.SEQNO
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    private String seqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSPRDCKPTDEF.CKPTPROG
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    private String ckptprog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSPRDCKPTDEF.CKPTPRDNAME
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    private String ckptprdname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSPRDCKPTDEF.CHKPERIOD
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    private String chkperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSPRDCKPTDEF.CKPTPARAM
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    private String ckptparam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSPRDCKPTDEF.REMARK
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSPRDCKPTDEF.VALIDFLAG
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    private String validflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSPRDCKPTDEF.GUID
     *
     * @return the value of SVPSPRDCKPTDEF.GUID
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSPRDCKPTDEF.GUID
     *
     * @param guid the value for SVPSPRDCKPTDEF.GUID
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSPRDCKPTDEF.PRDID
     *
     * @return the value of SVPSPRDCKPTDEF.PRDID
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public String getPrdid() {
        return prdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSPRDCKPTDEF.PRDID
     *
     * @param prdid the value for SVPSPRDCKPTDEF.PRDID
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public void setPrdid(String prdid) {
        this.prdid = prdid == null ? null : prdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSPRDCKPTDEF.SEQNO
     *
     * @return the value of SVPSPRDCKPTDEF.SEQNO
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public String getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSPRDCKPTDEF.SEQNO
     *
     * @param seqno the value for SVPSPRDCKPTDEF.SEQNO
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public void setSeqno(String seqno) {
        this.seqno = seqno == null ? null : seqno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSPRDCKPTDEF.CKPTPROG
     *
     * @return the value of SVPSPRDCKPTDEF.CKPTPROG
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public String getCkptprog() {
        return ckptprog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSPRDCKPTDEF.CKPTPROG
     *
     * @param ckptprog the value for SVPSPRDCKPTDEF.CKPTPROG
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public void setCkptprog(String ckptprog) {
        this.ckptprog = ckptprog == null ? null : ckptprog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSPRDCKPTDEF.CKPTPRDNAME
     *
     * @return the value of SVPSPRDCKPTDEF.CKPTPRDNAME
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public String getCkptprdname() {
        return ckptprdname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSPRDCKPTDEF.CKPTPRDNAME
     *
     * @param ckptprdname the value for SVPSPRDCKPTDEF.CKPTPRDNAME
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public void setCkptprdname(String ckptprdname) {
        this.ckptprdname = ckptprdname == null ? null : ckptprdname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSPRDCKPTDEF.CHKPERIOD
     *
     * @return the value of SVPSPRDCKPTDEF.CHKPERIOD
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public String getChkperiod() {
        return chkperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSPRDCKPTDEF.CHKPERIOD
     *
     * @param chkperiod the value for SVPSPRDCKPTDEF.CHKPERIOD
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public void setChkperiod(String chkperiod) {
        this.chkperiod = chkperiod == null ? null : chkperiod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSPRDCKPTDEF.CKPTPARAM
     *
     * @return the value of SVPSPRDCKPTDEF.CKPTPARAM
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public String getCkptparam() {
        return ckptparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSPRDCKPTDEF.CKPTPARAM
     *
     * @param ckptparam the value for SVPSPRDCKPTDEF.CKPTPARAM
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public void setCkptparam(String ckptparam) {
        this.ckptparam = ckptparam == null ? null : ckptparam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSPRDCKPTDEF.REMARK
     *
     * @return the value of SVPSPRDCKPTDEF.REMARK
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSPRDCKPTDEF.REMARK
     *
     * @param remark the value for SVPSPRDCKPTDEF.REMARK
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSPRDCKPTDEF.VALIDFLAG
     *
     * @return the value of SVPSPRDCKPTDEF.VALIDFLAG
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public String getValidflag() {
        return validflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSPRDCKPTDEF.VALIDFLAG
     *
     * @param validflag the value for SVPSPRDCKPTDEF.VALIDFLAG
     *
     * @mbggenerated Fri May 13 17:16:55 CST 2011
     */
    public void setValidflag(String validflag) {
        this.validflag = validflag == null ? null : validflag.trim();
    }
}