package pams.repository.model;

public class SvpsarchivectlKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSARCHIVECTL.ARCHIVEMONTH
     *
     * @mbggenerated Wed Jun 01 16:06:26 CST 2011
     */
    private String archivemonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVPSARCHIVECTL.ARCHIVEYEAR
     *
     * @mbggenerated Wed Jun 01 16:06:26 CST 2011
     */
    private String archiveyear;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSARCHIVECTL.ARCHIVEMONTH
     *
     * @return the value of SVPSARCHIVECTL.ARCHIVEMONTH
     *
     * @mbggenerated Wed Jun 01 16:06:26 CST 2011
     */
    public String getArchivemonth() {
        return archivemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSARCHIVECTL.ARCHIVEMONTH
     *
     * @param archivemonth the value for SVPSARCHIVECTL.ARCHIVEMONTH
     *
     * @mbggenerated Wed Jun 01 16:06:26 CST 2011
     */
    public void setArchivemonth(String archivemonth) {
        this.archivemonth = archivemonth == null ? null : archivemonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVPSARCHIVECTL.ARCHIVEYEAR
     *
     * @return the value of SVPSARCHIVECTL.ARCHIVEYEAR
     *
     * @mbggenerated Wed Jun 01 16:06:26 CST 2011
     */
    public String getArchiveyear() {
        return archiveyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVPSARCHIVECTL.ARCHIVEYEAR
     *
     * @param archiveyear the value for SVPSARCHIVECTL.ARCHIVEYEAR
     *
     * @mbggenerated Wed Jun 01 16:06:26 CST 2011
     */
    public void setArchiveyear(String archiveyear) {
        this.archiveyear = archiveyear == null ? null : archiveyear.trim();
    }
}