package pams.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SvpsprdsetmainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public SvpsprdsetmainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrdsetidIsNull() {
            addCriterion("PRDSETID is null");
            return (Criteria) this;
        }

        public Criteria andPrdsetidIsNotNull() {
            addCriterion("PRDSETID is not null");
            return (Criteria) this;
        }

        public Criteria andPrdsetidEqualTo(String value) {
            addCriterion("PRDSETID =", value, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidNotEqualTo(String value) {
            addCriterion("PRDSETID <>", value, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidGreaterThan(String value) {
            addCriterion("PRDSETID >", value, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidGreaterThanOrEqualTo(String value) {
            addCriterion("PRDSETID >=", value, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidLessThan(String value) {
            addCriterion("PRDSETID <", value, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidLessThanOrEqualTo(String value) {
            addCriterion("PRDSETID <=", value, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidLike(String value) {
            addCriterion("PRDSETID like", value, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidNotLike(String value) {
            addCriterion("PRDSETID not like", value, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidIn(List<String> values) {
            addCriterion("PRDSETID in", values, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidNotIn(List<String> values) {
            addCriterion("PRDSETID not in", values, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidBetween(String value1, String value2) {
            addCriterion("PRDSETID between", value1, value2, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetidNotBetween(String value1, String value2) {
            addCriterion("PRDSETID not between", value1, value2, "prdsetid");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameIsNull() {
            addCriterion("PRDSETNAME is null");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameIsNotNull() {
            addCriterion("PRDSETNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameEqualTo(String value) {
            addCriterion("PRDSETNAME =", value, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameNotEqualTo(String value) {
            addCriterion("PRDSETNAME <>", value, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameGreaterThan(String value) {
            addCriterion("PRDSETNAME >", value, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameGreaterThanOrEqualTo(String value) {
            addCriterion("PRDSETNAME >=", value, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameLessThan(String value) {
            addCriterion("PRDSETNAME <", value, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameLessThanOrEqualTo(String value) {
            addCriterion("PRDSETNAME <=", value, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameLike(String value) {
            addCriterion("PRDSETNAME like", value, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameNotLike(String value) {
            addCriterion("PRDSETNAME not like", value, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameIn(List<String> values) {
            addCriterion("PRDSETNAME in", values, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameNotIn(List<String> values) {
            addCriterion("PRDSETNAME not in", values, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameBetween(String value1, String value2) {
            addCriterion("PRDSETNAME between", value1, value2, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andPrdsetnameNotBetween(String value1, String value2) {
            addCriterion("PRDSETNAME not between", value1, value2, "prdsetname");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("STARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("STARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(String value) {
            addCriterion("STARTDATE =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(String value) {
            addCriterion("STARTDATE <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(String value) {
            addCriterion("STARTDATE >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("STARTDATE >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(String value) {
            addCriterion("STARTDATE <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(String value) {
            addCriterion("STARTDATE <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLike(String value) {
            addCriterion("STARTDATE like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotLike(String value) {
            addCriterion("STARTDATE not like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<String> values) {
            addCriterion("STARTDATE in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<String> values) {
            addCriterion("STARTDATE not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(String value1, String value2) {
            addCriterion("STARTDATE between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(String value1, String value2) {
            addCriterion("STARTDATE not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("ENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("ENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(String value) {
            addCriterion("ENDDATE =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(String value) {
            addCriterion("ENDDATE <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(String value) {
            addCriterion("ENDDATE >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(String value) {
            addCriterion("ENDDATE >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(String value) {
            addCriterion("ENDDATE <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(String value) {
            addCriterion("ENDDATE <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLike(String value) {
            addCriterion("ENDDATE like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotLike(String value) {
            addCriterion("ENDDATE not like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<String> values) {
            addCriterion("ENDDATE in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<String> values) {
            addCriterion("ENDDATE not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(String value1, String value2) {
            addCriterion("ENDDATE between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(String value1, String value2) {
            addCriterion("ENDDATE not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andOperidIsNull() {
            addCriterion("OPERID is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("OPERID is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("OPERID =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("OPERID <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("OPERID >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("OPERID >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("OPERID <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("OPERID <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("OPERID like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("OPERID not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("OPERID in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("OPERID not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("OPERID between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("OPERID not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNull() {
            addCriterion("OPERDATE is null");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNotNull() {
            addCriterion("OPERDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperdateEqualTo(Date value) {
            addCriterion("OPERDATE =", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotEqualTo(Date value) {
            addCriterion("OPERDATE <>", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThan(Date value) {
            addCriterion("OPERDATE >", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERDATE >=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThan(Date value) {
            addCriterion("OPERDATE <", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThanOrEqualTo(Date value) {
            addCriterion("OPERDATE <=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateIn(List<Date> values) {
            addCriterion("OPERDATE in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotIn(List<Date> values) {
            addCriterion("OPERDATE not in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateBetween(Date value1, Date value2) {
            addCriterion("OPERDATE between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotBetween(Date value1, Date value2) {
            addCriterion("OPERDATE not between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNull() {
            addCriterion("RECVERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNotNull() {
            addCriterion("RECVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecversionEqualTo(Long value) {
            addCriterion("RECVERSION =", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotEqualTo(Long value) {
            addCriterion("RECVERSION <>", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThan(Long value) {
            addCriterion("RECVERSION >", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThanOrEqualTo(Long value) {
            addCriterion("RECVERSION >=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThan(Long value) {
            addCriterion("RECVERSION <", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThanOrEqualTo(Long value) {
            addCriterion("RECVERSION <=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionIn(List<Long> values) {
            addCriterion("RECVERSION in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotIn(List<Long> values) {
            addCriterion("RECVERSION not in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionBetween(Long value1, Long value2) {
            addCriterion("RECVERSION between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotBetween(Long value1, Long value2) {
            addCriterion("RECVERSION not between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andMutexflagIsNull() {
            addCriterion("MUTEXFLAG is null");
            return (Criteria) this;
        }

        public Criteria andMutexflagIsNotNull() {
            addCriterion("MUTEXFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andMutexflagEqualTo(String value) {
            addCriterion("MUTEXFLAG =", value, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagNotEqualTo(String value) {
            addCriterion("MUTEXFLAG <>", value, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagGreaterThan(String value) {
            addCriterion("MUTEXFLAG >", value, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagGreaterThanOrEqualTo(String value) {
            addCriterion("MUTEXFLAG >=", value, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagLessThan(String value) {
            addCriterion("MUTEXFLAG <", value, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagLessThanOrEqualTo(String value) {
            addCriterion("MUTEXFLAG <=", value, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagLike(String value) {
            addCriterion("MUTEXFLAG like", value, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagNotLike(String value) {
            addCriterion("MUTEXFLAG not like", value, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagIn(List<String> values) {
            addCriterion("MUTEXFLAG in", values, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagNotIn(List<String> values) {
            addCriterion("MUTEXFLAG not in", values, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagBetween(String value1, String value2) {
            addCriterion("MUTEXFLAG between", value1, value2, "mutexflag");
            return (Criteria) this;
        }

        public Criteria andMutexflagNotBetween(String value1, String value2) {
            addCriterion("MUTEXFLAG not between", value1, value2, "mutexflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 21 10:11:26 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SVPSPRDSETMAIN
     *
     * @mbggenerated Thu Apr 21 10:11:26 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}